#ifndef RPROFREP_MSGPACK_DEFS_H
#define RPROFREP_MSGPACK_DEFS_H

enum {
    MSGPACK_EXT_STRING,
    MSGPACK_EXT_LOC,
    MSGPACK_EXT_API_DATA,
    MSGPACK_EXT_KERNEL,
    MSGPACK_EXT_CID
};

#endif // RPROFREP_MSGPACK_DEFS_H