/** THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE GILDA TOOL.
 * DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
 * ANY CHANGES MAY BE OVERWRITTEN BY SUBSEQUENT RUNS OF GILDA.
 */
 
#include <stdio.h>
#include "ratelprof.h"

// ---- Internal implementations ----

// Get the domain name
const char* __ratelprof_get_domain_name_impl(ratelprof_domain_t domain)
{
    if (domain >= RATELPROF_NB_DOMAIN) return "Unknown domain";
    const char* name = domains_data[domain].name;
    return name ? name : "Unknown domain";
}

// Get function name by ID
const char* __ratelprof_get_funame_by_id_impl(ratelprof_domain_t domain, ratelprof_api_id_t funid)
{
    if (domain >= RATELPROF_NB_DOMAIN || !domains_data[domain].get_funame_by_id) return NULL;
    return domains_data[domain].get_funame_by_id(funid);
}

// Get function ID by name
ratelprof_api_id_t __ratelprof_get_funid_by_name_impl(ratelprof_domain_t domain, const char* funame)
{
    if (domain >= RATELPROF_NB_DOMAIN || !domains_data[domain].get_funid_by_name) return -1;
    return domains_data[domain].get_funid_by_name(funame);
}

// Get function address by ID
void* __ratelprof_get_funaddr_by_id_impl(ratelprof_domain_t domain, ratelprof_api_id_t funid)
{
    if (domain >= RATELPROF_NB_DOMAIN || !domains_data[domain].get_funaddr_by_id) return NULL;
    return domains_data[domain].get_funaddr_by_id(funid);
}

// Enable domain
ratelprof_status_t __ratelprof_enable_domain_impl(ratelprof_domain_t domain)
{
    if (domain >= RATELPROF_NB_DOMAIN || !domains_data[domain].api_table_addr) 
        return RATELPROF_STATUS_UNKNOWN_DOMAIN;

    return ratelprof_enable_api_table(
        domains_data[domain].api_table_addr,
        domains_data[domain].functions_filtered_envname,
        domains_data[domain].filter_type_envname
    );
}

// Disable domain
ratelprof_status_t __ratelprof_disable_domain_impl(ratelprof_domain_t domain)
{
    if (domain >= RATELPROF_NB_DOMAIN || !domains_data[domain].api_table_addr) 
        return RATELPROF_STATUS_UNKNOWN_DOMAIN;

    return ratelprof_disable_api_table(domains_data[domain].api_table_addr);
}


ratelprof_status_t __ratelprof_start_impl(void)
{
    ratelprof_start_lifecycle();
    return RATELPROF_STATUS_SUCCESS;
}


ratelprof_status_t __ratelprof_stop_impl(void)
{
    ratelprof_stop_lifecycle();
    return RATELPROF_STATUS_SUCCESS;
}


ratelprof_status_t __ratelprof_init_impl(unsigned int ndomains)
{
	char* lib_path = NULL;
	unsetenv("LD_PRELOAD");

    ratelprof_status_t status = RATELPROF_STATUS_SUCCESS;
    RATELPROF_TRY(init_id_system());

	for (int i = 0; i < RATELPROF_NB_DOMAIN; i++)
	{
		RATELPROF_TRY(
			ratelprof_init_api_table(i, domains_data[i].api_table_addr, domains_data[i].nb_function),
			LOG(LOG_LEVEL_ERROR, "Cannot init API table for domain %d. %s (code %d)\n", i, get_error_string(status), status)
		);
		lib_path = getenv(domains_data[i].lib_path_envname);
		RATELPROF_TRY(
			ratelprof_populate_api_table(domains_data[i].api_table_addr, lib_path),
			LOG(LOG_LEVEL_ERROR, "Cannot populate API table for domain %d. %s (code %d)\n", i, get_error_string(status), status)
		);
	}
    RATELPROF_TRY(
        init_callback_system(ndomains),
        LOG(LOG_LEVEL_ERROR, "Failed to allocate callback system. %s (code %d)\n", get_error_string(status), status)
    );
        
    return status;
}



ratelprof_status_t __ratelprof_fini_impl(void)
{
    cleanup_id_system();
    ratelprof_status_t status = RATELPROF_STATUS_SUCCESS;
    
	for (int i = 0; i < RATELPROF_NB_DOMAIN; i++) {
		RATELPROF_TRY(
			ratelprof_cleanup_api_table(domains_data[i].api_table_addr),
			LOG(LOG_LEVEL_ERROR, "Cannot finalize API table for domain %d. %s (code %d)\n", i, get_error_string(status), status)
		);
	}
    fini_callback_system();
    return status;
}



// ---- Public API ----
RATELPROF_PUBLIC_API
const char* ratelprof_get_domain_name(ratelprof_domain_t domain)
{
    return __ratelprof_get_domain_name_impl(domain);
}

RATELPROF_PUBLIC_API
const char* ratelprof_get_funame_by_id(ratelprof_domain_t domain, ratelprof_api_id_t funid)
{
    return __ratelprof_get_funame_by_id_impl(domain, funid);
}

RATELPROF_PUBLIC_API
ratelprof_api_id_t ratelprof_get_funid_by_name(ratelprof_domain_t domain, const char* funame)
{
    return __ratelprof_get_funid_by_name_impl(domain, funame);
}

RATELPROF_PUBLIC_API
void* ratelprof_get_funaddr_by_id(ratelprof_domain_t domain, ratelprof_api_id_t funid)
{
    return __ratelprof_get_funaddr_by_id_impl(domain, funid);
}

RATELPROF_PUBLIC_API
ratelprof_status_t ratelprof_enable_domain(ratelprof_domain_t domain)
{
    return __ratelprof_enable_domain_impl(domain);
}

RATELPROF_PUBLIC_API
ratelprof_status_t ratelprof_disable_domain(ratelprof_domain_t domain)
{
    return __ratelprof_disable_domain_impl(domain);
}

RATELPROF_PUBLIC_API
ratelprof_status_t ratelprof_start(void)
{
    return __ratelprof_start_impl();
}

RATELPROF_PUBLIC_API
ratelprof_status_t ratelprof_stop(void)
{
    return __ratelprof_stop_impl();
}

RATELPROF_PUBLIC_API
ratelprof_status_t ratelprof_init(void)
{
    return __ratelprof_init_impl(RATELPROF_NB_DOMAIN);
}

RATELPROF_PUBLIC_API
ratelprof_status_t ratelprof_fini(void)
{
    return __ratelprof_fini_impl();
}

