CMAKE_MINIMUM_REQUIRED(VERSION 3.10)

FILE(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*.c")

ADD_LIBRARY(${EXT_PROJECT_NAME}-lib-dyn     SHARED ${SOURCES})
ADD_LIBRARY(${EXT_PROJECT_NAME}-lib-static  STATIC ${SOURCES})

TARGET_LINK_LIBRARIES(${EXT_PROJECT_NAME}-lib-dyn       ${CORE_PROJECT_NAME}-lib-dyn )
TARGET_LINK_LIBRARIES(${EXT_PROJECT_NAME}-lib-static    ${CORE_PROJECT_NAME}-lib-static)

TARGET_INCLUDE_DIRECTORIES(${EXT_PROJECT_NAME}-lib-dyn      PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
TARGET_INCLUDE_DIRECTORIES(${EXT_PROJECT_NAME}-lib-static   PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)

SET_TARGET_PROPERTIES(${EXT_PROJECT_NAME}-lib-dyn       PROPERTIES OUTPUT_NAME ${EXT_PROJECT_NAME})
SET_TARGET_PROPERTIES(${EXT_PROJECT_NAME}-lib-static    PROPERTIES OUTPUT_NAME ${EXT_PROJECT_NAME})

CONFIGURE_FILE(
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ratelprof_version.h.in
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ratelprof_version.h
    @ONLY
)