/** THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE GILDA TOOL.
 * DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
 * ANY CHANGES MAY BE OVERWRITTEN BY SUBSEQUENT RUNS OF GILDA. 
 */


#ifndef OMP_TGT_RTL_ARGS_H
#define OMP_TGT_RTL_ARGS_H

#include <ratelprof.h>
#include <ratelprof_ext.h>

#include "rprofrep_encode_context.h"
#include "utils/rprofrep_msgpack_ext.h"

#include "msgpack.h"

#if HAVE___tgt_rtl_query_async
//	int32_t device_id (int);
//	__tgt_async_info * AsyncInfoPtr (struct __tgt_async_info*);
//	int32_t retval (int);

static void write___tgt_rtl_query_async_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "AsyncInfoPtr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_query_async_args_to_buffer(args___tgt_rtl_query_async_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->AsyncInfoPtr);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_submit
//	int32_t device_id (int);
//	void * target_ptr (void *);
//	void * host_ptr (void *);
//	int64_t size (long);
//	int32_t retval (int);

static void write___tgt_rtl_data_submit_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 5);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "target_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_submit_args_to_buffer(args___tgt_rtl_data_submit_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->target_ptr);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_are_allocations_for_maps_on_apus_disabled
//	int retval (int);

static void write___tgt_rtl_are_allocations_for_maps_on_apus_disabled_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_are_allocations_for_maps_on_apus_disabled_args_to_buffer(args___tgt_rtl_are_allocations_for_maps_on_apus_disabled_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_notify_mapped
//	int32_t device_id (int);
//	void * host_ptr (void *);
//	int64_t size (long);
//	int32_t retval (int);

static void write___tgt_rtl_data_notify_mapped_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 4);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_notify_mapped_args_to_buffer(args___tgt_rtl_data_notify_mapped_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_submit_async
//	int32_t device_id (int);
//	void * target_ptr (void *);
//	void * host_ptr (void *);
//	int64_t size (long);
//	__tgt_async_info * AsyncInfo (struct __tgt_async_info*);
//	int32_t retval (int);

static void write___tgt_rtl_data_submit_async_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 6);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "target_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "AsyncInfo");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_submit_async_args_to_buffer(args___tgt_rtl_data_submit_async_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->target_ptr);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_uint(buf, (uintptr_t)args->AsyncInfo);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_init_async_info
//	int32_t device_id (int);
//	__tgt_async_info ** async_info_ptr (struct __tgt_async_info**);
//	int32_t retval (int);

static void write___tgt_rtl_init_async_info_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info **");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "async_info_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_init_async_info_args_to_buffer(args___tgt_rtl_init_async_info_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->async_info_ptr);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_is_data_exchangable
//	int32_t src_dev_id (int);
//	int32_t dst_dev_id (int);
//	int32_t retval (int);

static void write___tgt_rtl_is_data_exchangable_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "src_dev_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "dst_dev_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_is_data_exchangable_args_to_buffer(args___tgt_rtl_is_data_exchangable_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->src_dev_id);
	msgpack_encode_int(buf, args->dst_dev_id);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_retrieve_async
//	int32_t device_id (int);
//	void * host_ptr (void *);
//	void * target_ptr (void *);
//	int64_t size (long);
//	__tgt_async_info * AsyncInfo (struct __tgt_async_info*);
//	int32_t retval (int);

static void write___tgt_rtl_data_retrieve_async_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 6);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "target_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "AsyncInfo");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_retrieve_async_args_to_buffer(args___tgt_rtl_data_retrieve_async_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_uint(buf, (uintptr_t)args->target_ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_uint(buf, (uintptr_t)args->AsyncInfo);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_delete
//	int32_t device_id (int);
//	void * target_ptr (void *);
//	int32_t kind (int);
//	int32_t retval (int);

static void write___tgt_rtl_data_delete_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 4);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "target_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "kind");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_delete_args_to_buffer(args___tgt_rtl_data_delete_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->target_ptr);
	msgpack_encode_int(buf, args->kind);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_exchange_async
//	int32_t src_dev_id (int);
//	void * src_ptr (void *);
//	int32_t dst_dev_id (int);
//	void * dst_ptr (void *);
//	int64_t size (long);
//	__tgt_async_info * AsyncInfo (struct __tgt_async_info*);
//	int32_t retval (int);

static void write___tgt_rtl_data_exchange_async_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 7);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "src_dev_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "src_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "dst_dev_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "dst_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "AsyncInfo");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_exchange_async_args_to_buffer(args___tgt_rtl_data_exchange_async_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->src_dev_id);
	msgpack_encode_uint(buf, (uintptr_t)args->src_ptr);
	msgpack_encode_int(buf, args->dst_dev_id);
	msgpack_encode_uint(buf, (uintptr_t)args->dst_ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_uint(buf, (uintptr_t)args->AsyncInfo);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_prepopulate_page_table
//	int32_t device_id (int);
//	void * ptr (void *);
//	int64_t size (long);
//	int32_t retval (int);

static void write___tgt_rtl_prepopulate_page_table_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 4);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_prepopulate_page_table_args_to_buffer(args___tgt_rtl_prepopulate_page_table_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_exchange
//	int32_t src_dev_id (int);
//	void * src_ptr (void *);
//	int32_t dst_dev_id (int);
//	void * dst_ptr (void *);
//	int64_t size (long);
//	int32_t retval (int);

static void write___tgt_rtl_data_exchange_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 6);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "src_dev_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "src_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "dst_dev_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "dst_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_exchange_args_to_buffer(args___tgt_rtl_data_exchange_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->src_dev_id);
	msgpack_encode_uint(buf, (uintptr_t)args->src_ptr);
	msgpack_encode_int(buf, args->dst_dev_id);
	msgpack_encode_uint(buf, (uintptr_t)args->dst_ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_launch_kernel
//	int32_t device_id (int);
//	void * tgt_entry_ptr (void *);
//	void ** tgt_args (void **);
//	ptrdiff_t * tgt_offsets (long*);
//	KernelArgsTy * KernelArgs (struct KernelArgsTy*);
//	__tgt_async_info * AsyncInfo (struct __tgt_async_info*);
//	int32_t retval (int);

static void write___tgt_rtl_launch_kernel_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 7);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "tgt_entry_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void **");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "tgt_args");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "ptrdiff_t *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "tgt_offsets");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "KernelArgsTy *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "KernelArgs");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "AsyncInfo");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_launch_kernel_args_to_buffer(args___tgt_rtl_launch_kernel_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->tgt_entry_ptr);
	msgpack_encode_uint(buf, (uintptr_t)args->tgt_args);
	msgpack_encode_uint(buf, (uintptr_t)args->tgt_offsets);
	msgpack_encode_uint(buf, (uintptr_t)args->KernelArgs);
	msgpack_encode_uint(buf, (uintptr_t)args->AsyncInfo);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_is_valid_binary
//	__tgt_device_image * image (struct __tgt_device_image*);
//	int32_t retval (int);

static void write___tgt_rtl_is_valid_binary_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 2);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_device_image *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "image");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_is_valid_binary_args_to_buffer(args___tgt_rtl_is_valid_binary_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, (uintptr_t)args->image);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_retrieve
//	int32_t device_id (int);
//	void * host_ptr (void *);
//	void * target_ptr (void *);
//	int64_t size (long);
//	int32_t retval (int);

static void write___tgt_rtl_data_retrieve_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 5);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "target_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_retrieve_args_to_buffer(args___tgt_rtl_data_retrieve_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_uint(buf, (uintptr_t)args->target_ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_lock
//	int32_t device_id (int);
//	void * host_ptr (void *);
//	int64_t size (long);
//	void ** LockedHostPtr (void **);
//	int32_t retval (int);

static void write___tgt_rtl_data_lock_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 5);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void **");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "LockedHostPtr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_lock_args_to_buffer(args___tgt_rtl_data_lock_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_uint(buf, (uintptr_t)args->LockedHostPtr);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_supports_empty_images
//	int32_t retval (int);

static void write___tgt_rtl_supports_empty_images_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_supports_empty_images_args_to_buffer(args___tgt_rtl_supports_empty_images_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_destroy_event
//	int32_t device_id (int);
//	void * event (void *);
//	int32_t retval (int);

static void write___tgt_rtl_destroy_event_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "event");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_destroy_event_args_to_buffer(args___tgt_rtl_destroy_event_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->event);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_number_of_devices
//	int32_t retval (int);

static void write___tgt_rtl_number_of_devices_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_number_of_devices_args_to_buffer(args___tgt_rtl_number_of_devices_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_init_requires
//	int64_t RequiresFlags (long);
//	int64_t retval (long);

static void write___tgt_rtl_init_requires_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 2);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "RequiresFlags");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_init_requires_args_to_buffer(args___tgt_rtl_init_requires_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->RequiresFlags);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_notify_unmapped
//	int32_t device_id (int);
//	void * host_ptr (void *);
//	int32_t retval (int);

static void write___tgt_rtl_data_notify_unmapped_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_notify_unmapped_args_to_buffer(args___tgt_rtl_data_notify_unmapped_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_init_device_info
//	int32_t device_id (int);
//	__tgt_device_info * device_info_ptr (struct __tgt_device_info*);
//	const char ** err_str (const char **);
//	int32_t retval (int);

static void write___tgt_rtl_init_device_info_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 4);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_device_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_info_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "const char **");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "err_str");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_init_device_info_args_to_buffer(args___tgt_rtl_init_device_info_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->device_info_ptr);
	msgpack_encode_uint(buf, (uintptr_t)args->err_str);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_sync_event
//	int32_t device_id (int);
//	void * event (void *);
//	int32_t retval (int);

static void write___tgt_rtl_sync_event_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "event");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_sync_event_args_to_buffer(args___tgt_rtl_sync_event_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->event);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_synchronize
//	int32_t device_id (int);
//	__tgt_async_info * AsyncInfo (struct __tgt_async_info*);
//	int32_t retval (int);

static void write___tgt_rtl_synchronize_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "AsyncInfo");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_synchronize_args_to_buffer(args___tgt_rtl_synchronize_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->AsyncInfo);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_set_up_env


static void write___tgt_rtl_set_up_env_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 0);

}

static void write___tgt_rtl_set_up_env_args_to_buffer(args___tgt_rtl_set_up_env_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {

}

#endif

#if HAVE___tgt_rtl_data_unlock
//	int device_id (int);
//	void * host_ptr (void *);
//	int32_t retval (int);

static void write___tgt_rtl_data_unlock_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_unlock_args_to_buffer(args___tgt_rtl_data_unlock_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_is_fine_grained_memory_enabled
//	int retval (int);

static void write___tgt_rtl_is_fine_grained_memory_enabled_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_is_fine_grained_memory_enabled_args_to_buffer(args___tgt_rtl_is_fine_grained_memory_enabled_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_has_USM_capable_dGPU
//	int retval (int);

static void write___tgt_rtl_has_USM_capable_dGPU_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_has_USM_capable_dGPU_args_to_buffer(args___tgt_rtl_has_USM_capable_dGPU_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_has_apu_device
//	int retval (int);

static void write___tgt_rtl_has_apu_device_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_has_apu_device_args_to_buffer(args___tgt_rtl_has_apu_device_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_set_device_offset
//	int32_t DeviceIdOffset (int);
//	int32_t retval (int);

static void write___tgt_rtl_set_device_offset_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 2);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "DeviceIdOffset");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_set_device_offset_args_to_buffer(args___tgt_rtl_set_device_offset_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->DeviceIdOffset);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_launch_kernel_sync
//	int32_t device_id (int);
//	void * tgt_entry_ptr (void *);
//	void ** tgt_args (void **);
//	ptrdiff_t * tgt_offsets (long*);
//	KernelArgsTy * KernelArgs (struct KernelArgsTy*);
//	int32_t retval (int);

static void write___tgt_rtl_launch_kernel_sync_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 6);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "tgt_entry_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void **");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "tgt_args");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "ptrdiff_t *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "tgt_offsets");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "KernelArgsTy *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "KernelArgs");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_launch_kernel_sync_args_to_buffer(args___tgt_rtl_launch_kernel_sync_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->tgt_entry_ptr);
	msgpack_encode_uint(buf, (uintptr_t)args->tgt_args);
	msgpack_encode_uint(buf, (uintptr_t)args->tgt_offsets);
	msgpack_encode_uint(buf, (uintptr_t)args->KernelArgs);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_record_event
//	int32_t device_id (int);
//	void * event (void *);
//	__tgt_async_info * AsyncInfo (struct __tgt_async_info*);
//	int32_t retval (int);

static void write___tgt_rtl_record_event_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 4);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "event");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "AsyncInfo");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_record_event_args_to_buffer(args___tgt_rtl_record_event_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->event);
	msgpack_encode_uint(buf, (uintptr_t)args->AsyncInfo);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_set_info_flag
//	uint32_t NewInfoLevel (unsigned int);

static void write___tgt_rtl_set_info_flag_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "uint32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "NewInfoLevel");
}

static void write___tgt_rtl_set_info_flag_args_to_buffer(args___tgt_rtl_set_info_flag_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->NewInfoLevel);
}

#endif

#if HAVE___tgt_rtl_create_event
//	int32_t device_id (int);
//	void ** event (void **);
//	int32_t retval (int);

static void write___tgt_rtl_create_event_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 3);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void **");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "event");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_create_event_args_to_buffer(args___tgt_rtl_create_event_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->event);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_print_device_info
//	int32_t device_id (int);

static void write___tgt_rtl_print_device_info_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
}

static void write___tgt_rtl_print_device_info_args_to_buffer(args___tgt_rtl_print_device_info_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
}

#endif

#if HAVE___tgt_rtl_get_function
//	__tgt_device_binary binary ({
//		uintptr_t handle (unsigned long);
//	});
//	const char * name (const char *);
//	void ** kernel_ptr (void **);
//	int32_t retval (int);

static void write___tgt_rtl_get_function_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 4);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_device_binary");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "binary");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "const char *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "name");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void **");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "kernel_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_get_function_args_to_buffer(args___tgt_rtl_get_function_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_array(buf, 1);
	msgpack_encode_int(buf, args->binary.handle);
	msgpack_encode_uint(buf, (uintptr_t)args->name);
	msgpack_encode_uint(buf, (uintptr_t)args->kernel_ptr);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_init_plugin
//	int32_t retval (int);

static void write___tgt_rtl_init_plugin_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_init_plugin_args_to_buffer(args___tgt_rtl_init_plugin_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_number_of_team_procs
//	int device_id (int);
//	int32_t retval (int);

static void write___tgt_rtl_number_of_team_procs_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 2);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_number_of_team_procs_args_to_buffer(args___tgt_rtl_number_of_team_procs_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_wait_event
//	int32_t device_id (int);
//	void * event (void *);
//	__tgt_async_info * AsyncInfo (struct __tgt_async_info*);
//	int32_t retval (int);

static void write___tgt_rtl_wait_event_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 4);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "event");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_async_info *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "AsyncInfo");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_wait_event_args_to_buffer(args___tgt_rtl_wait_event_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_uint(buf, (uintptr_t)args->event);
	msgpack_encode_uint(buf, (uintptr_t)args->AsyncInfo);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_data_alloc
//	int32_t device_id (int);
//	int64_t size (long);
//	void * host_ptr (void *);
//	int32_t kind (int);
//	void * retval (void *);

static void write___tgt_rtl_data_alloc_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 5);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "host_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "kind");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_data_alloc_args_to_buffer(args___tgt_rtl_data_alloc_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_uint(buf, (uintptr_t)args->host_ptr);
	msgpack_encode_int(buf, args->kind);
	msgpack_encode_uint(buf, (uintptr_t)args->retval);
}

#endif

#if HAVE___tgt_rtl_init_device
//	int32_t device_id (int);
//	int32_t retval (int);

static void write___tgt_rtl_init_device_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 2);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_id");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_init_device_args_to_buffer(args___tgt_rtl_init_device_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->device_id);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_get_global
//	__tgt_device_binary binary ({
//		uintptr_t handle (unsigned long);
//	});
//	uint64_t size (unsigned long);
//	const char * name (const char *);
//	void ** device_ptr (void **);
//	int32_t retval (int);

static void write___tgt_rtl_get_global_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 5);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "__tgt_device_binary");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "binary");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "uint64_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "size");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "const char *");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "name");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "void **");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "device_ptr");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int32_t");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_get_global_args_to_buffer(args___tgt_rtl_get_global_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_array(buf, 1);
	msgpack_encode_int(buf, args->binary.handle);
	msgpack_encode_int(buf, args->size);
	msgpack_encode_uint(buf, (uintptr_t)args->name);
	msgpack_encode_uint(buf, (uintptr_t)args->device_ptr);
	msgpack_encode_int(buf, args->retval);
}

#endif

#if HAVE___tgt_rtl_requested_prepopulate_gpu_page_table
//	int retval (int);

static void write___tgt_rtl_requested_prepopulate_gpu_page_table_params_to_buffer(rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_uint(buf, 1);
	rprofrep_msgpack_ext_encode_string(ctx, buf, "int");
	rprofrep_msgpack_ext_encode_string(ctx, buf, "retval");
}

static void write___tgt_rtl_requested_prepopulate_gpu_page_table_args_to_buffer(args___tgt_rtl_requested_prepopulate_gpu_page_table_t* args, rprofrep_encode_context_t* ctx, msgpack_buffer_t* buf) {
	msgpack_encode_int(buf, args->retval);
}

#endif


#endif // OMP_TGT_RTL_ARGS_H
