CMAKE_MINIMUM_REQUIRED(VERSION 3.10)

FILE(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*.c")

ADD_LIBRARY(${CORE_PROJECT_NAME}-lib-dyn     SHARED ${SOURCES})
ADD_LIBRARY(${CORE_PROJECT_NAME}-lib-static  STATIC ${SOURCES})

TARGET_INCLUDE_DIRECTORIES(${CORE_PROJECT_NAME}-lib-dyn      PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
TARGET_INCLUDE_DIRECTORIES(${CORE_PROJECT_NAME}-lib-static   PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)

SET_TARGET_PROPERTIES(${CORE_PROJECT_NAME}-lib-dyn       PROPERTIES OUTPUT_NAME ${CORE_PROJECT_NAME})
SET_TARGET_PROPERTIES(${CORE_PROJECT_NAME}-lib-static    PROPERTIES OUTPUT_NAME ${CORE_PROJECT_NAME})