CMAKE_MINIMUM_REQUIRED(VERSION 3.10)

FILE(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*.c")

ADD_LIBRARY(${WRAPPER_PROJECT_NAME}-lib-dyn    SHARED ${SOURCES})
ADD_LIBRARY(${WRAPPER_PROJECT_NAME}-lib-static STATIC ${SOURCES})

TARGET_LINK_LIBRARIES(${WRAPPER_PROJECT_NAME}-lib-dyn       ${CORE_PROJECT_NAME}-lib-dyn    ${EXT_PROJECT_NAME}-lib-dyn)

SET_TARGET_PROPERTIES(${WRAPPER_PROJECT_NAME}-lib-dyn       PROPERTIES OUTPUT_NAME ${WRAPPER_PROJECT_NAME})
SET_TARGET_PROPERTIES(${WRAPPER_PROJECT_NAME}-lib-static    PROPERTIES OUTPUT_NAME ${WRAPPER_PROJECT_NAME})

# SET_TARGET_PROPERTIES(${WRAPPER_PROJECT_NAME}-lib-dyn ${WRAPPER_PROJECT_NAME}-lib-static PROPERTIES
# #TODO: Find a way to avoid hipcc dependency
#     CXX_COMPILER ${HIPCC_COMPILER}
#     C_COMPILER  ${HIPCC_COMPILER}
# )

TARGET_INCLUDE_DIRECTORIES(${WRAPPER_PROJECT_NAME}-lib-static   PUBLIC
    $<TARGET_PROPERTY:${CORE_PROJECT_NAME}-lib-static,INTERFACE_INCLUDE_DIRECTORIES>
    $<TARGET_PROPERTY:${EXT_PROJECT_NAME}-lib-static,INTERFACE_INCLUDE_DIRECTORIES>
)