INCLUDE(cmake/check_available_functions.cmake)

FUNCTION(CHECK_MPI_SYMBOLS)
	FIND_PACKAGE(MPI)

	IF (MPI_C_FOUND)
		# set environment
		SET(CMAKE_REQUIRED_FLAGS 		"${MPI_C_COMPILE_OPTIONS}")
		SET(CMAKE_REQUIRED_DEFINITIONS 	"${MPI_C_COMPILE_DEFINITIONS}")
		SET(CMAKE_REQUIRED_INCLUDES 	"${MPI_C_INCLUDE_DIRS}")
		SET(CMAKE_REQUIRED_LIBRARIES 	"${MPI_C_LIBRARIES}")

		# check for symbol
        CHECK_AVAILABLE_FUNCTION(mpi mpi.h ${CMAKE_SOURCE_DIR}/src/core/include/utils/config)

		INCLUDE_DIRECTORIES(${MPI_C_INCLUDE_DIRS})
	ENDIF ()
ENDFUNCTION()