INCLUDE(cmake/check_available_functions.cmake)
INCLUDE(cmake/findROCm.cmake)

FUNCTION(CHECK_ROCM_SYMBOLS)
	SET(CONFIG_DIR ${CMAKE_SOURCE_DIR}/src/core/include/utils/config)

	SET(CMAKE_REQUIRED_INCLUDES ${ROCM_INCLUDE_PATH})

	# HSA CHECK
	CHECK_AVAILABLE_FUNCTION(hsa "hsa/hsa.h;hsa/hsa_ext_amd.h" ${CONFIG_DIR})

	# HIP CHECK
	SET(CMAKE_REQUIRED_DEFINITIONS 	"-D__HIP_PLATFORM_AMD__")
	CHECK_AVAILABLE_FUNCTION(hip hip/hip_runtime.h ${CONFIG_DIR})
	UNSET(CMAKE_REQUIRED_DEFINITIONS)
	UNSET(CMAKE_REQUIRED_INCLUDES)

	# OMP CHECK
	CHECK_AVAILABLE_FUNCTION(omp_routine ${ROCM_LLVM_INCLUDE_PATH}/omp.h ${CONFIG_DIR})
	CHECK_AVAILABLE_FUNCTION(omp_tgt_rtl "NO_CHECK"    					 ${CONFIG_DIR})

	INCLUDE_DIRECTORIES(${ROCM_INCLUDE_PATH})
	INCLUDE_DIRECTORIES(${ROCM_LLVM_INCLUDE_PATH})
ENDFUNCTION()