if(NOT DEFINED ROCM_PATH)
    if(DEFINED ENV{ROCM_PATH})
        set(ROCM_PATH "$ENV{ROCM_PATH}" CACHE PATH "Path to ROCm installation")
    else()
        set(ROCM_PATH "/opt/rocm" CACHE PATH "Path to ROCm installation")
    endif()
    set(ROCM_INCLUDE_PATH       "${ROCM_PATH}/include"      CACHE PATH "Path to ROCm include directory")
    set(ROCM_LLVM_INCLUDE_PATH  "${ROCM_PATH}/llvm/include" CACHE PATH "Path to ROCm LLVM include directory")
endif()
