/* # THIS FILE HAS BEEN AUTOMATICALLY GENERATED BY THE GILDA TOOL.
 * # DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
 * # ANY CHANGES MAY BE OVERWRITTEN BY SUBSEQUENT RUNS OF GILDA.
 */

#include "api_table_manager.h"
#include "hip/hip_runtime.h"

extern api_table_t hip_api_table;

hipError_t hipTexRefSetMipmapFilterMode(textureReference* texRef, enum hipTextureFilterMode fm) {
	return ((__hipTexRefSetMipmapFilterMode_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetMipmapFilterMode])(texRef, fm);
};

hipError_t hipMemcpyHtoA(hipArray_t dstArray, size_t dstOffset, const void * srcHost, size_t count) {
	return ((__hipMemcpyHtoA_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyHtoA])(dstArray, dstOffset, srcHost, count);
};

hipError_t hipCtxGetApiVersion(hipCtx_t ctx, int * apiVersion) {
	return ((__hipCtxGetApiVersion_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxGetApiVersion])(ctx, apiVersion);
};

hipError_t hipDeviceGetName(char * name, int len, hipDevice_t device) {
	return ((__hipDeviceGetName_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetName])(name, len, device);
};

hipError_t hipStreamIsCapturing(hipStream_t stream, hipStreamCaptureStatus * pCaptureStatus) {
	return ((__hipStreamIsCapturing_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamIsCapturing])(stream, pCaptureStatus);
};

hipError_t hipStreamAttachMemAsync(hipStream_t stream, void * dev_ptr, size_t length, unsigned int flags) {
	return ((__hipStreamAttachMemAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamAttachMemAsync])(stream, dev_ptr, length, flags);
};

hipError_t hipFreeArray(hipArray_t array) {
	return ((__hipFreeArray_t)hip_api_table.api_ptr[HIP_API_ID_hipFreeArray])(array);
};

hipError_t hipSetDeviceFlags(unsigned int flags) {
	return ((__hipSetDeviceFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipSetDeviceFlags])(flags);
};

hipError_t hipIpcOpenEventHandle(hipEvent_t * event, hipIpcEventHandle_t handle) {
	return ((__hipIpcOpenEventHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipIpcOpenEventHandle])(event, handle);
};

hipError_t hipModuleLoad(hipModule_t * module, const char * fname) {
	return ((__hipModuleLoad_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleLoad])(module, fname);
};

hipError_t hipExternalMemoryGetMappedBuffer(void ** devPtr, hipExternalMemory_t extMem, const hipExternalMemoryBufferDesc * bufferDesc) {
	return ((__hipExternalMemoryGetMappedBuffer_t)hip_api_table.api_ptr[HIP_API_ID_hipExternalMemoryGetMappedBuffer])(devPtr, extMem, bufferDesc);
};

hipError_t hipMemImportFromShareableHandle(hipMemGenericAllocationHandle_t * handle, void * osHandle, hipMemAllocationHandleType shHandleType) {
	return ((__hipMemImportFromShareableHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipMemImportFromShareableHandle])(handle, osHandle, shHandleType);
};

hipError_t hipMemcpyDtoH(void * dst, hipDeviceptr_t src, size_t sizeBytes) {
	return ((__hipMemcpyDtoH_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyDtoH])(dst, src, sizeBytes);
};

hipError_t hipStreamEndCapture(hipStream_t stream, hipGraph_t * pGraph) {
	return ((__hipStreamEndCapture_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamEndCapture])(stream, pGraph);
};

hipError_t hipGraphMemFreeNodeGetParams(hipGraphNode_t node, void * dev_ptr) {
	return ((__hipGraphMemFreeNodeGetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemFreeNodeGetParams])(node, dev_ptr);
};

hipError_t hipThreadExchangeStreamCaptureMode(hipStreamCaptureMode * mode) {
	return ((__hipThreadExchangeStreamCaptureMode_t)hip_api_table.api_ptr[HIP_API_ID_hipThreadExchangeStreamCaptureMode])(mode);
};

hipError_t hipModuleUnload(hipModule_t module) {
	return ((__hipModuleUnload_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleUnload])(module);
};

hipError_t hipModuleOccupancyMaxPotentialBlockSize(int * gridSize, int * blockSize, hipFunction_t f, size_t dynSharedMemPerBlk, int blockSizeLimit) {
	return ((__hipModuleOccupancyMaxPotentialBlockSize_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleOccupancyMaxPotentialBlockSize])(gridSize, blockSize, f, dynSharedMemPerBlk, blockSizeLimit);
};

hipError_t hipMemcpyParam2D(const hip_Memcpy2D * pCopy) {
	return ((__hipMemcpyParam2D_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyParam2D])(pCopy);
};

hipError_t hipPeekAtLastError() {
	return ((__hipPeekAtLastError_t)hip_api_table.api_ptr[HIP_API_ID_hipPeekAtLastError])();
};

hipError_t hipMemRelease(hipMemGenericAllocationHandle_t handle) {
	return ((__hipMemRelease_t)hip_api_table.api_ptr[HIP_API_ID_hipMemRelease])(handle);
};

hipError_t hipDeviceGetSharedMemConfig(hipSharedMemConfig * pConfig) {
	return ((__hipDeviceGetSharedMemConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetSharedMemConfig])(pConfig);
};

hipError_t hipUserObjectRelease(hipUserObject_t object, unsigned int count) {
	return ((__hipUserObjectRelease_t)hip_api_table.api_ptr[HIP_API_ID_hipUserObjectRelease])(object, count);
};

hipError_t hipStreamWriteValue32(hipStream_t stream, void * ptr, uint32_t value, unsigned int flags) {
	return ((__hipStreamWriteValue32_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamWriteValue32])(stream, ptr, value, flags);
};

hipError_t hipMemAllocHost(void ** ptr, size_t size) {
	return ((__hipMemAllocHost_t)hip_api_table.api_ptr[HIP_API_ID_hipMemAllocHost])(ptr, size);
};

hipError_t hipGraphCreate(hipGraph_t * pGraph, unsigned int flags) {
	return ((__hipGraphCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphCreate])(pGraph, flags);
};

hipError_t hipModuleOccupancyMaxPotentialBlockSizeWithFlags(int * gridSize, int * blockSize, hipFunction_t f, size_t dynSharedMemPerBlk, int blockSizeLimit, unsigned int flags) {
	return ((__hipModuleOccupancyMaxPotentialBlockSizeWithFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleOccupancyMaxPotentialBlockSizeWithFlags])(gridSize, blockSize, f, dynSharedMemPerBlk, blockSizeLimit, flags);
};

hipError_t hipMalloc3DArray(hipArray_t * array, const struct hipChannelFormatDesc * desc, struct hipExtent extent, unsigned int flags) {
	return ((__hipMalloc3DArray_t)hip_api_table.api_ptr[HIP_API_ID_hipMalloc3DArray])(array, desc, extent, flags);
};

hipError_t hipCtxGetCacheConfig(hipFuncCache_t * cacheConfig) {
	return ((__hipCtxGetCacheConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxGetCacheConfig])(cacheConfig);
};

hipError_t hipModuleLaunchCooperativeKernel(hipFunction_t f, unsigned int gridDimX, unsigned int gridDimY, unsigned int gridDimZ, unsigned int blockDimX, unsigned int blockDimY, unsigned int blockDimZ, unsigned int sharedMemBytes, hipStream_t stream, void ** kernelParams) {
	return ((__hipModuleLaunchCooperativeKernel_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleLaunchCooperativeKernel])(f, gridDimX, gridDimY, gridDimZ, blockDimX, blockDimY, blockDimZ, sharedMemBytes, stream, kernelParams);
};

hipError_t hipTexRefGetAddressMode(enum hipTextureAddressMode * pam, const textureReference* texRef, int dim) {
	return ((__hipTexRefGetAddressMode_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetAddressMode])(pam, texRef, dim);
};

hipError_t hipGraphEventWaitNodeSetEvent(hipGraphNode_t node, hipEvent_t event) {
	return ((__hipGraphEventWaitNodeSetEvent_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphEventWaitNodeSetEvent])(node, event);
};

hipError_t hipDeviceGetDefaultMemPool(hipMemPool_t * mem_pool, int device) {
	return ((__hipDeviceGetDefaultMemPool_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetDefaultMemPool])(mem_pool, device);
};

hipError_t hipMemPoolTrimTo(hipMemPool_t mem_pool, size_t min_bytes_to_hold) {
	return ((__hipMemPoolTrimTo_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolTrimTo])(mem_pool, min_bytes_to_hold);
};

hipError_t hipGraphUpload(hipGraphExec_t graphExec, hipStream_t stream) {
	return ((__hipGraphUpload_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphUpload])(graphExec, stream);
};

hipError_t hipExternalMemoryGetMappedMipmappedArray(hipMipmappedArray_t * mipmap, hipExternalMemory_t extMem, const hipExternalMemoryMipmappedArrayDesc * mipmapDesc) {
	return ((__hipExternalMemoryGetMappedMipmappedArray_t)hip_api_table.api_ptr[HIP_API_ID_hipExternalMemoryGetMappedMipmappedArray])(mipmap, extMem, mipmapDesc);
};

hipError_t hipGraphExternalSemaphoresWaitNodeSetParams(hipGraphNode_t hNode, const hipExternalSemaphoreWaitNodeParams * nodeParams) {
	return ((__hipGraphExternalSemaphoresWaitNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExternalSemaphoresWaitNodeSetParams])(hNode, nodeParams);
};

hipError_t hipMemcpyToSymbol(const void * symbol, const void * src, size_t sizeBytes, size_t offset, hipMemcpyKind kind) {
	return ((__hipMemcpyToSymbol_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyToSymbol])(symbol, src, sizeBytes, offset, kind);
};

hipError_t hipGraphAddMemsetNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, const hipMemsetParams * pMemsetParams) {
	return ((__hipGraphAddMemsetNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddMemsetNode])(pGraphNode, graph, pDependencies, numDependencies, pMemsetParams);
};

hipError_t hipGraphClone(hipGraph_t * pGraphClone, hipGraph_t originalGraph) {
	return ((__hipGraphClone_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphClone])(pGraphClone, originalGraph);
};

hipError_t hipExtGetLastError() {
	return ((__hipExtGetLastError_t)hip_api_table.api_ptr[HIP_API_ID_hipExtGetLastError])();
};

hipError_t hipGraphKernelNodeGetAttribute(hipGraphNode_t hNode, hipKernelNodeAttrID attr, hipKernelNodeAttrValue * value) {
	return ((__hipGraphKernelNodeGetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphKernelNodeGetAttribute])(hNode, attr, value);
};

hipError_t hipEventRecord(hipEvent_t event, hipStream_t stream) {
	return ((__hipEventRecord_t)hip_api_table.api_ptr[HIP_API_ID_hipEventRecord])(event, stream);
};

hipError_t hipMemGetAllocationPropertiesFromHandle(hipMemAllocationProp * prop, hipMemGenericAllocationHandle_t handle) {
	return ((__hipMemGetAllocationPropertiesFromHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipMemGetAllocationPropertiesFromHandle])(prop, handle);
};

hipError_t hipGraphAddEventWaitNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, hipEvent_t event) {
	return ((__hipGraphAddEventWaitNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddEventWaitNode])(pGraphNode, graph, pDependencies, numDependencies, event);
};

hipError_t hipMemPoolImportPointer(void ** dev_ptr, hipMemPool_t mem_pool, hipMemPoolPtrExportData * export_data) {
	return ((__hipMemPoolImportPointer_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolImportPointer])(dev_ptr, mem_pool, export_data);
};

hipError_t hipFree(void * ptr) {
	return ((__hipFree_t)hip_api_table.api_ptr[HIP_API_ID_hipFree])(ptr);
};

hipError_t hipGraphEventRecordNodeGetEvent(hipGraphNode_t node, hipEvent_t * event_out) {
	return ((__hipGraphEventRecordNodeGetEvent_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphEventRecordNodeGetEvent])(node, event_out);
};

hipError_t hipMalloc(void ** ptr, size_t size) {
	return ((__hipMalloc_t)hip_api_table.api_ptr[HIP_API_ID_hipMalloc])(ptr, size);
};

hipError_t hipMemcpyWithStream(void * dst, const void * src, size_t sizeBytes, hipMemcpyKind kind, hipStream_t stream) {
	return ((__hipMemcpyWithStream_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyWithStream])(dst, src, sizeBytes, kind, stream);
};

hipError_t hipDrvMemcpy3DAsync(const HIP_MEMCPY3D* pCopy, hipStream_t stream) {
	return ((__hipDrvMemcpy3DAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipDrvMemcpy3DAsync])(pCopy, stream);
};

hipError_t hipGraphAddMemAllocNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, hipMemAllocNodeParams * pNodeParams) {
	return ((__hipGraphAddMemAllocNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddMemAllocNode])(pGraphNode, graph, pDependencies, numDependencies, pNodeParams);
};

hipError_t hipHostMalloc(void ** ptr, size_t size, unsigned int flags) {
	return ((__hipHostMalloc_t)hip_api_table.api_ptr[HIP_API_ID_hipHostMalloc])(ptr, size, flags);
};

hipError_t hipGraphMemcpyNodeGetParams(hipGraphNode_t node, hipMemcpy3DParms * pNodeParams) {
	return ((__hipGraphMemcpyNodeGetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemcpyNodeGetParams])(node, pNodeParams);
};

hipError_t hipTexRefSetFlags(textureReference * texRef, unsigned int Flags) {
	return ((__hipTexRefSetFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetFlags])(texRef, Flags);
};

hipError_t hipMemPoolImportFromShareableHandle(hipMemPool_t * mem_pool, void * shared_handle, hipMemAllocationHandleType handle_type, unsigned int flags) {
	return ((__hipMemPoolImportFromShareableHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolImportFromShareableHandle])(mem_pool, shared_handle, handle_type, flags);
};

hipError_t hipGraphNodeSetEnabled(hipGraphExec_t hGraphExec, hipGraphNode_t hNode, unsigned int isEnabled) {
	return ((__hipGraphNodeSetEnabled_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphNodeSetEnabled])(hGraphExec, hNode, isEnabled);
};

hipError_t hipTexRefSetMipmapLevelBias(textureReference * texRef, float bias) {
	return ((__hipTexRefSetMipmapLevelBias_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetMipmapLevelBias])(texRef, bias);
};

hipError_t hipStreamWaitValue32(hipStream_t stream, void * ptr, uint32_t value, unsigned int flags, uint32_t mask) {
	return ((__hipStreamWaitValue32_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamWaitValue32])(stream, ptr, value, flags, mask);
};

hipError_t hipMipmappedArrayDestroy(hipMipmappedArray_t hMipmappedArray) {
	return ((__hipMipmappedArrayDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipMipmappedArrayDestroy])(hMipmappedArray);
};

hipError_t hipCtxDestroy(hipCtx_t ctx) {
	return ((__hipCtxDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxDestroy])(ctx);
};

hipError_t hipDeviceReset() {
	return ((__hipDeviceReset_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceReset])();
};

hipError_t hipMemPrefetchAsync(const void * dev_ptr, size_t count, int device, hipStream_t stream) {
	return ((__hipMemPrefetchAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPrefetchAsync])(dev_ptr, count, device, stream);
};

hipError_t hipMemsetD16(hipDeviceptr_t dest, unsigned short value, size_t count) {
	return ((__hipMemsetD16_t)hip_api_table.api_ptr[HIP_API_ID_hipMemsetD16])(dest, value, count);
};

hipError_t hipMemcpy2DAsync(void * dst, size_t dpitch, const void * src, size_t spitch, size_t width, size_t height, hipMemcpyKind kind, hipStream_t stream) {
	return ((__hipMemcpy2DAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy2DAsync])(dst, dpitch, src, spitch, width, height, kind, stream);
};

hipError_t hipDevicePrimaryCtxSetFlags(hipDevice_t dev, unsigned int flags) {
	return ((__hipDevicePrimaryCtxSetFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipDevicePrimaryCtxSetFlags])(dev, flags);
};

hipError_t hipGraphInstantiateWithFlags(hipGraphExec_t * pGraphExec, hipGraph_t graph, unsigned long long flags) {
	return ((__hipGraphInstantiateWithFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphInstantiateWithFlags])(pGraphExec, graph, flags);
};

hipError_t hipGraphAddEmptyNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies) {
	return ((__hipGraphAddEmptyNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddEmptyNode])(pGraphNode, graph, pDependencies, numDependencies);
};

hipError_t hipFreeMipmappedArray(hipMipmappedArray_t mipmappedArray) {
	return ((__hipFreeMipmappedArray_t)hip_api_table.api_ptr[HIP_API_ID_hipFreeMipmappedArray])(mipmappedArray);
};

hipError_t hipArrayCreate(hipArray_t * pHandle, const HIP_ARRAY_DESCRIPTOR * pAllocateArray) {
	return ((__hipArrayCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipArrayCreate])(pHandle, pAllocateArray);
};

hipError_t hipUnbindTexture(const textureReference * tex) {
	return ((__hipUnbindTexture_t)hip_api_table.api_ptr[HIP_API_ID_hipUnbindTexture])(tex);
};

hipError_t hipCtxPopCurrent(hipCtx_t * ctx) {
	return ((__hipCtxPopCurrent_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxPopCurrent])(ctx);
};

hipError_t hipMemsetD16Async(hipDeviceptr_t dest, unsigned short value, size_t count, hipStream_t stream) {
	return ((__hipMemsetD16Async_t)hip_api_table.api_ptr[HIP_API_ID_hipMemsetD16Async])(dest, value, count, stream);
};

hipError_t hipTexObjectGetResourceDesc(HIP_RESOURCE_DESC * pResDesc, hipTextureObject_t texObject) {
	return ((__hipTexObjectGetResourceDesc_t)hip_api_table.api_ptr[HIP_API_ID_hipTexObjectGetResourceDesc])(pResDesc, texObject);
};

hipError_t hipLaunchKernel(const void * function_address, dim3 numBlocks, dim3 dimBlocks, void ** args, size_t sharedMemBytes, hipStream_t stream) {
	return ((__hipLaunchKernel_t)hip_api_table.api_ptr[HIP_API_ID_hipLaunchKernel])(function_address, numBlocks, dimBlocks, args, sharedMemBytes, stream);
};

hipError_t hipGraphMemsetNodeGetParams(hipGraphNode_t node, hipMemsetParams * pNodeParams) {
	return ((__hipGraphMemsetNodeGetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemsetNodeGetParams])(node, pNodeParams);
};

hipError_t hipHostGetFlags(unsigned int * flagsPtr, void * hostPtr) {
	return ((__hipHostGetFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipHostGetFlags])(flagsPtr, hostPtr);
};

hipError_t hipGraphLaunch(hipGraphExec_t graphExec, hipStream_t stream) {
	return ((__hipGraphLaunch_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphLaunch])(graphExec, stream);
};

hipError_t hipMemcpyAsync(void * dst, const void * src, size_t sizeBytes, hipMemcpyKind kind, hipStream_t stream) {
	return ((__hipMemcpyAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyAsync])(dst, src, sizeBytes, kind, stream);
};

hipError_t hipMallocArray(hipArray_t * array, const hipChannelFormatDesc * desc, size_t width, size_t height, unsigned int flags) {
	return ((__hipMallocArray_t)hip_api_table.api_ptr[HIP_API_ID_hipMallocArray])(array, desc, width, height, flags);
};

hipError_t hipFuncSetCacheConfig(const void * func, hipFuncCache_t config) {
	return ((__hipFuncSetCacheConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipFuncSetCacheConfig])(func, config);
};

hipError_t hipMallocManaged(void ** dev_ptr, size_t size, unsigned int flags) {
	return ((__hipMallocManaged_t)hip_api_table.api_ptr[HIP_API_ID_hipMallocManaged])(dev_ptr, size, flags);
};

const char * hipApiName(uint32_t id) {
	return ((__hipApiName_t)hip_api_table.api_ptr[HIP_API_ID_hipApiName])(id);
};

hipError_t hipFreeHost(void * ptr) {
	return ((__hipFreeHost_t)hip_api_table.api_ptr[HIP_API_ID_hipFreeHost])(ptr);
};

hipError_t hipCtxGetCurrent(hipCtx_t * ctx) {
	return ((__hipCtxGetCurrent_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxGetCurrent])(ctx);
};

hipError_t hipDestroySurfaceObject(hipSurfaceObject_t surfaceObject) {
	return ((__hipDestroySurfaceObject_t)hip_api_table.api_ptr[HIP_API_ID_hipDestroySurfaceObject])(surfaceObject);
};

hipError_t hipMallocPitch(void ** ptr, size_t * pitch, size_t width, size_t height) {
	return ((__hipMallocPitch_t)hip_api_table.api_ptr[HIP_API_ID_hipMallocPitch])(ptr, pitch, width, height);
};

hipError_t hipStreamGetCaptureInfo(hipStream_t stream, hipStreamCaptureStatus * pCaptureStatus, unsigned long long * pId) {
	return ((__hipStreamGetCaptureInfo_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamGetCaptureInfo])(stream, pCaptureStatus, pId);
};

hipError_t hipStreamUpdateCaptureDependencies(hipStream_t stream, hipGraphNode_t * dependencies, size_t numDependencies, unsigned int flags) {
	return ((__hipStreamUpdateCaptureDependencies_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamUpdateCaptureDependencies])(stream, dependencies, numDependencies, flags);
};

hipError_t hipHostAlloc(void ** ptr, size_t size, unsigned int flags) {
	return ((__hipHostAlloc_t)hip_api_table.api_ptr[HIP_API_ID_hipHostAlloc])(ptr, size, flags);
};

hipError_t hipMemsetD8(hipDeviceptr_t dest, unsigned char value, size_t count) {
	return ((__hipMemsetD8_t)hip_api_table.api_ptr[HIP_API_ID_hipMemsetD8])(dest, value, count);
};

hipError_t hipMemset3DAsync(hipPitchedPtr pitchedDevPtr, int value, hipExtent extent, hipStream_t stream) {
	return ((__hipMemset3DAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemset3DAsync])(pitchedDevPtr, value, extent, stream);
};

hipError_t hipMemcpyParam2DAsync(const hip_Memcpy2D * pCopy, hipStream_t stream) {
	return ((__hipMemcpyParam2DAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyParam2DAsync])(pCopy, stream);
};

hipError_t hipDrvGetErrorName(hipError_t hipError, const char ** errorString) {
	return ((__hipDrvGetErrorName_t)hip_api_table.api_ptr[HIP_API_ID_hipDrvGetErrorName])(hipError, errorString);
};

hipError_t hipPointerSetAttribute(const void * value, hipPointer_attribute attribute, hipDeviceptr_t ptr) {
	return ((__hipPointerSetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipPointerSetAttribute])(value, attribute, ptr);
};

hipError_t hipMemGetInfo(size_t * free, size_t * total) {
	return ((__hipMemGetInfo_t)hip_api_table.api_ptr[HIP_API_ID_hipMemGetInfo])(free, total);
};

hipError_t __hipPushCallConfiguration(dim3 gridDim, dim3 blockDim, size_t sharedMem, hipStream_t stream) {
	return ((____hipPushCallConfiguration_t)hip_api_table.api_ptr[HIP_API_ID___hipPushCallConfiguration])(gridDim, blockDim, sharedMem, stream);
};

hipError_t hipTexRefGetFormat(hipArray_Format * pFormat, int * pNumChannels, const textureReference * texRef) {
	return ((__hipTexRefGetFormat_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetFormat])(pFormat, pNumChannels, texRef);
};

hipError_t hipMemExportToShareableHandle(void * shareableHandle, hipMemGenericAllocationHandle_t handle, hipMemAllocationHandleType handleType, unsigned long long flags) {
	return ((__hipMemExportToShareableHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipMemExportToShareableHandle])(shareableHandle, handle, handleType, flags);
};

hipError_t hipTexRefGetFilterMode(enum hipTextureFilterMode * pfm, const textureReference* texRef) {
	return ((__hipTexRefGetFilterMode_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetFilterMode])(pfm, texRef);
};

hipError_t hipGraphHostNodeSetParams(hipGraphNode_t node, const hipHostNodeParams * pNodeParams) {
	return ((__hipGraphHostNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphHostNodeSetParams])(node, pNodeParams);
};

hipError_t hipGraphGetNodes(hipGraph_t graph, hipGraphNode_t * nodes, size_t * numNodes) {
	return ((__hipGraphGetNodes_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphGetNodes])(graph, nodes, numNodes);
};

hipError_t hipCtxGetDevice(hipDevice_t * device) {
	return ((__hipCtxGetDevice_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxGetDevice])(device);
};

hipError_t hipGetSymbolAddress(void ** devPtr, const void * symbol) {
	return ((__hipGetSymbolAddress_t)hip_api_table.api_ptr[HIP_API_ID_hipGetSymbolAddress])(devPtr, symbol);
};

hipError_t hipStreamGetCaptureInfo_v2(hipStream_t stream, hipStreamCaptureStatus * captureStatus_out, unsigned long long * id_out, hipGraph_t * graph_out, const hipGraphNode_t ** dependencies_out, size_t * numDependencies_out) {
	return ((__hipStreamGetCaptureInfo_v2_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamGetCaptureInfo_v2])(stream, captureStatus_out, id_out, graph_out, dependencies_out, numDependencies_out);
};

hipError_t hipGetSymbolSize(size_t* size, const void * symbol) {
	return ((__hipGetSymbolSize_t)hip_api_table.api_ptr[HIP_API_ID_hipGetSymbolSize])(size, symbol);
};

hipError_t hipGraphExecHostNodeSetParams(hipGraphExec_t hGraphExec, hipGraphNode_t node, const hipHostNodeParams * pNodeParams) {
	return ((__hipGraphExecHostNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecHostNodeSetParams])(hGraphExec, node, pNodeParams);
};

hipError_t hipMemPoolSetAttribute(hipMemPool_t mem_pool, hipMemPoolAttr attr, void * value) {
	return ((__hipMemPoolSetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolSetAttribute])(mem_pool, attr, value);
};

hipError_t hipDeviceSetMemPool(int device, hipMemPool_t mem_pool) {
	return ((__hipDeviceSetMemPool_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceSetMemPool])(device, mem_pool);
};

hipError_t hipConfigureCall(dim3 gridDim, dim3 blockDim, size_t sharedMem, hipStream_t stream) {
	return ((__hipConfigureCall_t)hip_api_table.api_ptr[HIP_API_ID_hipConfigureCall])(gridDim, blockDim, sharedMem, stream);
};

hipError_t hipMipmappedArrayCreate(hipMipmappedArray_t * pHandle, HIP_ARRAY3D_DESCRIPTOR * pMipmappedArrayDesc, unsigned int numMipmapLevels) {
	return ((__hipMipmappedArrayCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipMipmappedArrayCreate])(pHandle, pMipmappedArrayDesc, numMipmapLevels);
};

hipError_t hipHostRegister(void * hostPtr, size_t sizeBytes, unsigned int flags) {
	return ((__hipHostRegister_t)hip_api_table.api_ptr[HIP_API_ID_hipHostRegister])(hostPtr, sizeBytes, flags);
};

hipError_t hipBindTextureToArray(const textureReference * tex, hipArray_const_t array, const hipChannelFormatDesc * desc) {
	return ((__hipBindTextureToArray_t)hip_api_table.api_ptr[HIP_API_ID_hipBindTextureToArray])(tex, array, desc);
};

hipError_t hipMallocHost(void ** ptr, size_t size) {
	return ((__hipMallocHost_t)hip_api_table.api_ptr[HIP_API_ID_hipMallocHost])(ptr, size);
};

hipError_t hipMemcpyPeer(void * dst, int dstDeviceId, const void * src, int srcDeviceId, size_t sizeBytes) {
	return ((__hipMemcpyPeer_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyPeer])(dst, dstDeviceId, src, srcDeviceId, sizeBytes);
};

hipError_t hipOccupancyMaxActiveBlocksPerMultiprocessor(int * numBlocks, const void * f, int blockSize, size_t dynSharedMemPerBlk) {
	return ((__hipOccupancyMaxActiveBlocksPerMultiprocessor_t)hip_api_table.api_ptr[HIP_API_ID_hipOccupancyMaxActiveBlocksPerMultiprocessor])(numBlocks, f, blockSize, dynSharedMemPerBlk);
};

hipError_t hipDeviceGetAttribute(int * pi, hipDeviceAttribute_t attr, int deviceId) {
	return ((__hipDeviceGetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetAttribute])(pi, attr, deviceId);
};

hipError_t hipDevicePrimaryCtxReset(hipDevice_t dev) {
	return ((__hipDevicePrimaryCtxReset_t)hip_api_table.api_ptr[HIP_API_ID_hipDevicePrimaryCtxReset])(dev);
};

hipError_t hipTexRefSetAddress(size_t * ByteOffset, textureReference * texRef, hipDeviceptr_t dptr, size_t bytes) {
	return ((__hipTexRefSetAddress_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetAddress])(ByteOffset, texRef, dptr, bytes);
};

hipError_t hipGraphicsResourceGetMappedPointer(void ** devPtr, size_t* size, hipGraphicsResource_t resource) {
	return ((__hipGraphicsResourceGetMappedPointer_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphicsResourceGetMappedPointer])(devPtr, size, resource);
};

hipError_t hipCtxSetSharedMemConfig(hipSharedMemConfig config) {
	return ((__hipCtxSetSharedMemConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxSetSharedMemConfig])(config);
};

hipError_t hipGraphExternalSemaphoresSignalNodeGetParams(hipGraphNode_t hNode, hipExternalSemaphoreSignalNodeParams * params_out) {
	return ((__hipGraphExternalSemaphoresSignalNodeGetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExternalSemaphoresSignalNodeGetParams])(hNode, params_out);
};

hipError_t hipArrayDestroy(hipArray_t array) {
	return ((__hipArrayDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipArrayDestroy])(array);
};

hipError_t hipFreeAsync(void * dev_ptr, hipStream_t stream) {
	return ((__hipFreeAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipFreeAsync])(dev_ptr, stream);
};

hipError_t hipArray3DGetDescriptor(HIP_ARRAY3D_DESCRIPTOR * pArrayDescriptor, hipArray_t array) {
	return ((__hipArray3DGetDescriptor_t)hip_api_table.api_ptr[HIP_API_ID_hipArray3DGetDescriptor])(pArrayDescriptor, array);
};

hipError_t hipDeviceGetPCIBusId(char * pciBusId, int len, int device) {
	return ((__hipDeviceGetPCIBusId_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetPCIBusId])(pciBusId, len, device);
};

hipError_t hipGraphAddMemFreeNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, void * dev_ptr) {
	return ((__hipGraphAddMemFreeNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddMemFreeNode])(pGraphNode, graph, pDependencies, numDependencies, dev_ptr);
};

hipError_t hipArray3DCreate(hipArray_t * array, const HIP_ARRAY3D_DESCRIPTOR * pAllocateArray) {
	return ((__hipArray3DCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipArray3DCreate])(array, pAllocateArray);
};

hipError_t hipGraphExternalSemaphoresSignalNodeSetParams(hipGraphNode_t hNode, const hipExternalSemaphoreSignalNodeParams * nodeParams) {
	return ((__hipGraphExternalSemaphoresSignalNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExternalSemaphoresSignalNodeSetParams])(hNode, nodeParams);
};

hipError_t hipTexRefGetBorderColor(float * pBorderColor, const textureReference* texRef) {
	return ((__hipTexRefGetBorderColor_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetBorderColor])(pBorderColor, texRef);
};

hipError_t hipModuleGetGlobal(hipDeviceptr_t * dptr, size_t* bytes, hipModule_t hmod, const char * name) {
	return ((__hipModuleGetGlobal_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleGetGlobal])(dptr, bytes, hmod, name);
};

hipError_t hipMallocMipmappedArray(hipMipmappedArray_t * mipmappedArray, const struct hipChannelFormatDesc * desc, struct hipExtent extent, unsigned int numLevels, unsigned int flags) {
	return ((__hipMallocMipmappedArray_t)hip_api_table.api_ptr[HIP_API_ID_hipMallocMipmappedArray])(mipmappedArray, desc, extent, numLevels, flags);
};

hipError_t hipProfilerStart() {
	return ((__hipProfilerStart_t)hip_api_table.api_ptr[HIP_API_ID_hipProfilerStart])();
};

hipError_t hipGraphExecMemcpyNodeSetParams(hipGraphExec_t hGraphExec, hipGraphNode_t node, hipMemcpy3DParms * pNodeParams) {
	return ((__hipGraphExecMemcpyNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecMemcpyNodeSetParams])(hGraphExec, node, pNodeParams);
};

hipError_t hipEventSynchronize(hipEvent_t event) {
	return ((__hipEventSynchronize_t)hip_api_table.api_ptr[HIP_API_ID_hipEventSynchronize])(event);
};

hipError_t hipMemPoolExportPointer(hipMemPoolPtrExportData * export_data, void * dev_ptr) {
	return ((__hipMemPoolExportPointer_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolExportPointer])(export_data, dev_ptr);
};

hipError_t hipHostUnregister(void * hostPtr) {
	return ((__hipHostUnregister_t)hip_api_table.api_ptr[HIP_API_ID_hipHostUnregister])(hostPtr);
};

hipError_t hipMemset2D(void * dst, size_t pitch, int value, size_t width, size_t height) {
	return ((__hipMemset2D_t)hip_api_table.api_ptr[HIP_API_ID_hipMemset2D])(dst, pitch, value, width, height);
};

hipError_t hipMemcpy2DFromArray(void * dst, size_t dpitch, hipArray_const_t src, size_t wOffset, size_t hOffset, size_t width, size_t height, hipMemcpyKind kind) {
	return ((__hipMemcpy2DFromArray_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy2DFromArray])(dst, dpitch, src, wOffset, hOffset, width, height, kind);
};

hipError_t hipMemAddressReserve(void ** ptr, size_t size, size_t alignment, void * addr, unsigned long long flags) {
	return ((__hipMemAddressReserve_t)hip_api_table.api_ptr[HIP_API_ID_hipMemAddressReserve])(ptr, size, alignment, addr, flags);
};

hipError_t hipFuncSetSharedMemConfig(const void * func, hipSharedMemConfig config) {
	return ((__hipFuncSetSharedMemConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipFuncSetSharedMemConfig])(func, config);
};

hipError_t hipDestroyTextureObject(hipTextureObject_t textureObject) {
	return ((__hipDestroyTextureObject_t)hip_api_table.api_ptr[HIP_API_ID_hipDestroyTextureObject])(textureObject);
};

hipError_t hipTexRefSetMaxAnisotropy(textureReference* texRef, unsigned int maxAniso) {
	return ((__hipTexRefSetMaxAnisotropy_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetMaxAnisotropy])(texRef, maxAniso);
};

hipError_t hipTexRefSetAddress2D(textureReference* texRef, const HIP_ARRAY_DESCRIPTOR * desc, hipDeviceptr_t dptr, size_t Pitch) {
	return ((__hipTexRefSetAddress2D_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetAddress2D])(texRef, desc, dptr, Pitch);
};

hipError_t hipGetDevice(int * deviceId) {
	return ((__hipGetDevice_t)hip_api_table.api_ptr[HIP_API_ID_hipGetDevice])(deviceId);
};

hipError_t hipDeviceGetGraphMemAttribute(int device, hipGraphMemAttributeType attr, void * value) {
	return ((__hipDeviceGetGraphMemAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetGraphMemAttribute])(device, attr, value);
};

hipError_t hipGraphicsSubResourceGetMappedArray(hipArray_t * array, hipGraphicsResource_t resource, unsigned int arrayIndex, unsigned int mipLevel) {
	return ((__hipGraphicsSubResourceGetMappedArray_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphicsSubResourceGetMappedArray])(array, resource, arrayIndex, mipLevel);
};

hipError_t hipGraphMemcpyNodeSetParamsToSymbol(hipGraphNode_t node, const void * symbol, const void * src, size_t count, size_t offset, hipMemcpyKind kind) {
	return ((__hipGraphMemcpyNodeSetParamsToSymbol_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemcpyNodeSetParamsToSymbol])(node, symbol, src, count, offset, kind);
};

hipError_t hipStreamCreate(hipStream_t * stream) {
	return ((__hipStreamCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamCreate])(stream);
};

hipError_t hipGraphNodeGetDependencies(hipGraphNode_t node, hipGraphNode_t * pDependencies, size_t* pNumDependencies) {
	return ((__hipGraphNodeGetDependencies_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphNodeGetDependencies])(node, pDependencies, pNumDependencies);
};

hipError_t hipBindTextureToMipmappedArray(const textureReference* tex, hipMipmappedArray_const_t mipmappedArray, const hipChannelFormatDesc* desc) {
	return ((__hipBindTextureToMipmappedArray_t)hip_api_table.api_ptr[HIP_API_ID_hipBindTextureToMipmappedArray])(tex, mipmappedArray, desc);
};

hipError_t hipGraphExecUpdate(hipGraphExec_t hGraphExec, hipGraph_t hGraph, hipGraphNode_t * hErrorNode_out, hipGraphExecUpdateResult * updateResult_out) {
	return ((__hipGraphExecUpdate_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecUpdate])(hGraphExec, hGraph, hErrorNode_out, updateResult_out);
};

hipError_t hipDeviceTotalMem(size_t* bytes, hipDevice_t device) {
	return ((__hipDeviceTotalMem_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceTotalMem])(bytes, device);
};

hipError_t hipMemcpyFromArray(void * dst, hipArray_const_t srcArray, size_t wOffset, size_t hOffset, size_t count, hipMemcpyKind kind) {
	return ((__hipMemcpyFromArray_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyFromArray])(dst, srcArray, wOffset, hOffset, count, kind);
};

hipError_t hipEventCreateWithFlags(hipEvent_t * event, unsigned int flags) {
	return ((__hipEventCreateWithFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipEventCreateWithFlags])(event, flags);
};

hipError_t hipDeviceGetCacheConfig(hipFuncCache_t * cacheConfig) {
	return ((__hipDeviceGetCacheConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetCacheConfig])(cacheConfig);
};

hipError_t hipDriverGetVersion(int * driverVersion) {
	return ((__hipDriverGetVersion_t)hip_api_table.api_ptr[HIP_API_ID_hipDriverGetVersion])(driverVersion);
};

hipError_t hipGraphMemcpyNodeSetParams1D(hipGraphNode_t node, void * dst, const void * src, size_t count, hipMemcpyKind kind) {
	return ((__hipGraphMemcpyNodeSetParams1D_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemcpyNodeSetParams1D])(node, dst, src, count, kind);
};

hipError_t hipTexRefSetMipmapLevelClamp(textureReference* texRef, float minMipMapLevelClamp, float maxMipMapLevelClamp) {
	return ((__hipTexRefSetMipmapLevelClamp_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetMipmapLevelClamp])(texRef, minMipMapLevelClamp, maxMipMapLevelClamp);
};

hipError_t hipGraphMemAllocNodeGetParams(hipGraphNode_t node, hipMemAllocNodeParams * pNodeParams) {
	return ((__hipGraphMemAllocNodeGetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemAllocNodeGetParams])(node, pNodeParams);
};

hipError_t hipTexObjectDestroy(hipTextureObject_t texObject) {
	return ((__hipTexObjectDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipTexObjectDestroy])(texObject);
};

hipError_t hipExtStreamCreateWithCUMask(hipStream_t * stream, uint32_t cuMaskSize, const uint32_t * cuMask) {
	return ((__hipExtStreamCreateWithCUMask_t)hip_api_table.api_ptr[HIP_API_ID_hipExtStreamCreateWithCUMask])(stream, cuMaskSize, cuMask);
};

hipError_t __hipPopCallConfiguration(dim3 * gridDim, dim3 * blockDim, size_t * sharedMem, hipStream_t * stream) {
	return ((____hipPopCallConfiguration_t)hip_api_table.api_ptr[HIP_API_ID___hipPopCallConfiguration])(gridDim, blockDim, sharedMem, stream);
};

hipError_t hipMemRangeGetAttribute(void * data, size_t data_size, hipMemRangeAttribute attribute, const void * dev_ptr, size_t count) {
	return ((__hipMemRangeGetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipMemRangeGetAttribute])(data, data_size, attribute, dev_ptr, count);
};

hipError_t hipMemMap(void * ptr, size_t size, size_t offset, hipMemGenericAllocationHandle_t handle, unsigned long long flags) {
	return ((__hipMemMap_t)hip_api_table.api_ptr[HIP_API_ID_hipMemMap])(ptr, size, offset, handle, flags);
};

hipError_t hipStreamSynchronize(hipStream_t stream) {
	return ((__hipStreamSynchronize_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamSynchronize])(stream);
};

hipError_t hipUserObjectCreate(hipUserObject_t * object_out, void * ptr, hipHostFn_t destroy, unsigned int initialRefcount, unsigned int flags) {
	return ((__hipUserObjectCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipUserObjectCreate])(object_out, ptr, destroy, initialRefcount, flags);
};

hipError_t hipGetMipmappedArrayLevel(hipArray_t * levelArray, hipMipmappedArray_const_t mipmappedArray, unsigned int level) {
	return ((__hipGetMipmappedArrayLevel_t)hip_api_table.api_ptr[HIP_API_ID_hipGetMipmappedArrayLevel])(levelArray, mipmappedArray, level);
};

hipError_t hipMemcpyHtoD(hipDeviceptr_t dst, void * src, size_t sizeBytes) {
	return ((__hipMemcpyHtoD_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyHtoD])(dst, src, sizeBytes);
};

hipError_t hipMemGetAddressRange(hipDeviceptr_t * pbase, size_t * psize, hipDeviceptr_t dptr) {
	return ((__hipMemGetAddressRange_t)hip_api_table.api_ptr[HIP_API_ID_hipMemGetAddressRange])(pbase, psize, dptr);
};

hipError_t hipGraphAddMemcpyNodeFromSymbol(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, void * dst, const void * symbol, size_t count, size_t offset, hipMemcpyKind kind) {
	return ((__hipGraphAddMemcpyNodeFromSymbol_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddMemcpyNodeFromSymbol])(pGraphNode, graph, pDependencies, numDependencies, dst, symbol, count, offset, kind);
};

hipError_t hipMemPtrGetInfo(void * ptr, size_t* size) {
	return ((__hipMemPtrGetInfo_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPtrGetInfo])(ptr, size);
};

hipError_t hipTexRefSetMipmappedArray(textureReference* texRef, struct hipMipmappedArray * mipmappedArray, unsigned int Flags) {
	return ((__hipTexRefSetMipmappedArray_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetMipmappedArray])(texRef, mipmappedArray, Flags);
};

hipError_t hipImportExternalSemaphore(hipExternalSemaphore_t * extSem_out, const hipExternalSemaphoreHandleDesc * semHandleDesc) {
	return ((__hipImportExternalSemaphore_t)hip_api_table.api_ptr[HIP_API_ID_hipImportExternalSemaphore])(extSem_out, semHandleDesc);
};

hipError_t hipStreamWaitEvent(hipStream_t stream, hipEvent_t event, unsigned int flags) {
	return ((__hipStreamWaitEvent_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamWaitEvent])(stream, event, flags);
};

hipError_t hipGetDeviceCount(int * count) {
	return ((__hipGetDeviceCount_t)hip_api_table.api_ptr[HIP_API_ID_hipGetDeviceCount])(count);
};

hipError_t hipGraphKernelNodeCopyAttributes(hipGraphNode_t hSrc, hipGraphNode_t hDst) {
	return ((__hipGraphKernelNodeCopyAttributes_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphKernelNodeCopyAttributes])(hSrc, hDst);
};

hipError_t hipDestroyExternalSemaphore(hipExternalSemaphore_t extSem) {
	return ((__hipDestroyExternalSemaphore_t)hip_api_table.api_ptr[HIP_API_ID_hipDestroyExternalSemaphore])(extSem);
};

hipError_t hipGraphMemcpyNodeSetParams(hipGraphNode_t node, const hipMemcpy3DParms* pNodeParams) {
	return ((__hipGraphMemcpyNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemcpyNodeSetParams])(node, pNodeParams);
};

hipError_t hipStreamQuery(hipStream_t stream) {
	return ((__hipStreamQuery_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamQuery])(stream);
};

hipError_t hipGraphMemsetNodeSetParams(hipGraphNode_t node, const hipMemsetParams * pNodeParams) {
	return ((__hipGraphMemsetNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemsetNodeSetParams])(node, pNodeParams);
};

hipError_t hipRuntimeGetVersion(int * runtimeVersion) {
	return ((__hipRuntimeGetVersion_t)hip_api_table.api_ptr[HIP_API_ID_hipRuntimeGetVersion])(runtimeVersion);
};

hipError_t hipArrayGetDescriptor(HIP_ARRAY_DESCRIPTOR* pArrayDescriptor, hipArray_t array) {
	return ((__hipArrayGetDescriptor_t)hip_api_table.api_ptr[HIP_API_ID_hipArrayGetDescriptor])(pArrayDescriptor, array);
};

hipError_t hipMemsetD32Async(hipDeviceptr_t dst, int value, size_t count, hipStream_t stream) {
	return ((__hipMemsetD32Async_t)hip_api_table.api_ptr[HIP_API_ID_hipMemsetD32Async])(dst, value, count, stream);
};

hipError_t hipCtxGetSharedMemConfig(hipSharedMemConfig * pConfig) {
	return ((__hipCtxGetSharedMemConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxGetSharedMemConfig])(pConfig);
};

hipError_t hipModuleLoadDataEx(hipModule_t * module, const void * image, unsigned int numOptions, hipJitOption * options, void ** optionValues) {
	return ((__hipModuleLoadDataEx_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleLoadDataEx])(module, image, numOptions, options, optionValues);
};

hipError_t hipMemPoolExportToShareableHandle(void * shared_handle, hipMemPool_t mem_pool, hipMemAllocationHandleType handle_type, unsigned int flags) {
	return ((__hipMemPoolExportToShareableHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolExportToShareableHandle])(shared_handle, mem_pool, handle_type, flags);
};

hipError_t hipMallocFromPoolAsync(void ** dev_ptr, size_t size, hipMemPool_t mem_pool, hipStream_t stream) {
	return ((__hipMallocFromPoolAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMallocFromPoolAsync])(dev_ptr, size, mem_pool, stream);
};

hipError_t hipSetDevice(int deviceId) {
	return ((__hipSetDevice_t)hip_api_table.api_ptr[HIP_API_ID_hipSetDevice])(deviceId);
};

hipError_t hipMallocAsync(void ** dev_ptr, size_t size, hipStream_t stream) {
	return ((__hipMallocAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMallocAsync])(dev_ptr, size, stream);
};

hipError_t hipDeviceGet(hipDevice_t * device, int ordinal) {
	return ((__hipDeviceGet_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGet])(device, ordinal);
};

hipError_t hipMemsetAsync(void * dst, int value, size_t sizeBytes, hipStream_t stream) {
	return ((__hipMemsetAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemsetAsync])(dst, value, sizeBytes, stream);
};

hipError_t hipMemSetAccess(void * ptr, size_t size, const hipMemAccessDesc * desc, size_t count) {
	return ((__hipMemSetAccess_t)hip_api_table.api_ptr[HIP_API_ID_hipMemSetAccess])(ptr, size, desc, count);
};

hipError_t hipMemsetD32(hipDeviceptr_t dest, int value, size_t count) {
	return ((__hipMemsetD32_t)hip_api_table.api_ptr[HIP_API_ID_hipMemsetD32])(dest, value, count);
};

hipError_t hipGetDeviceFlags(unsigned int * flags) {
	return ((__hipGetDeviceFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipGetDeviceFlags])(flags);
};

hipError_t hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(int * numBlocks, const void * f, int blockSize, size_t dynSharedMemPerBlk, unsigned int flags) {
	return ((__hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags])(numBlocks, f, blockSize, dynSharedMemPerBlk, flags);
};

hipError_t hipDeviceGetUuid(hipUUID * uuid, hipDevice_t device) {
	return ((__hipDeviceGetUuid_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetUuid])(uuid, device);
};

hipError_t hipMemcpy2D(void * dst, size_t dpitch, const void * src, size_t spitch, size_t width, size_t height, hipMemcpyKind kind) {
	return ((__hipMemcpy2D_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy2D])(dst, dpitch, src, spitch, width, height, kind);
};

hipError_t hipArrayGetInfo(hipChannelFormatDesc * desc, hipExtent * extent, unsigned int * flags, hipArray_t array) {
	return ((__hipArrayGetInfo_t)hip_api_table.api_ptr[HIP_API_ID_hipArrayGetInfo])(desc, extent, flags, array);
};

hipError_t hipUserObjectRetain(hipUserObject_t object, unsigned int count) {
	return ((__hipUserObjectRetain_t)hip_api_table.api_ptr[HIP_API_ID_hipUserObjectRetain])(object, count);
};

hipError_t hipGraphicsMapResources(int count, hipGraphicsResource_t * resources, hipStream_t stream) {
	return ((__hipGraphicsMapResources_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphicsMapResources])(count, resources, stream);
};

hipError_t hipMemcpyHtoDAsync(hipDeviceptr_t dst, void * src, size_t sizeBytes, hipStream_t stream) {
	return ((__hipMemcpyHtoDAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyHtoDAsync])(dst, src, sizeBytes, stream);
};

hipError_t hipTexObjectGetTextureDesc(HIP_TEXTURE_DESC * pTexDesc, hipTextureObject_t texObject) {
	return ((__hipTexObjectGetTextureDesc_t)hip_api_table.api_ptr[HIP_API_ID_hipTexObjectGetTextureDesc])(pTexDesc, texObject);
};

hipError_t hipMemGetAccess(unsigned long long * flags, const hipMemLocation * location, void * ptr) {
	return ((__hipMemGetAccess_t)hip_api_table.api_ptr[HIP_API_ID_hipMemGetAccess])(flags, location, ptr);
};

hipError_t hipMemcpy2DToArrayAsync(hipArray_t dst, size_t wOffset, size_t hOffset, const void * src, size_t spitch, size_t width, size_t height, hipMemcpyKind kind, hipStream_t stream) {
	return ((__hipMemcpy2DToArrayAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy2DToArrayAsync])(dst, wOffset, hOffset, src, spitch, width, height, kind, stream);
};

hipError_t hipTexRefGetAddress(hipDeviceptr_t * dev_ptr, const textureReference* texRef) {
	return ((__hipTexRefGetAddress_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetAddress])(dev_ptr, texRef);
};

hipError_t hipGraphNodeGetType(hipGraphNode_t node, hipGraphNodeType * pType) {
	return ((__hipGraphNodeGetType_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphNodeGetType])(node, pType);
};

hipError_t hipStreamGetFlags(hipStream_t stream, unsigned int * flags) {
	return ((__hipStreamGetFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamGetFlags])(stream, flags);
};

hipError_t hipModuleOccupancyMaxActiveBlocksPerMultiprocessor(int * numBlocks, hipFunction_t f, int blockSize, size_t dynSharedMemPerBlk) {
	return ((__hipModuleOccupancyMaxActiveBlocksPerMultiprocessor_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleOccupancyMaxActiveBlocksPerMultiprocessor])(numBlocks, f, blockSize, dynSharedMemPerBlk);
};

hipError_t hipMemset2DAsync(void * dst, size_t pitch, int value, size_t width, size_t height, hipStream_t stream) {
	return ((__hipMemset2DAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemset2DAsync])(dst, pitch, value, width, height, stream);
};

hipError_t hipMemcpyFromSymbol(void * dst, const void * symbol, size_t sizeBytes, size_t offset, hipMemcpyKind kind) {
	return ((__hipMemcpyFromSymbol_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyFromSymbol])(dst, symbol, sizeBytes, offset, kind);
};

hipError_t hipHostFree(void * ptr) {
	return ((__hipHostFree_t)hip_api_table.api_ptr[HIP_API_ID_hipHostFree])(ptr);
};

hipError_t hipExtLaunchKernel(const void * function_address, dim3 numBlocks, dim3 dimBlocks, void ** args, size_t sharedMemBytes, hipStream_t stream, hipEvent_t startEvent, hipEvent_t stopEvent, int flags) {
	return ((__hipExtLaunchKernel_t)hip_api_table.api_ptr[HIP_API_ID_hipExtLaunchKernel])(function_address, numBlocks, dimBlocks, args, sharedMemBytes, stream, startEvent, stopEvent, flags);
};

hipError_t hipMemcpyFromSymbolAsync(void * dst, const void * symbol, size_t sizeBytes, size_t offset, hipMemcpyKind kind, hipStream_t stream) {
	return ((__hipMemcpyFromSymbolAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyFromSymbolAsync])(dst, symbol, sizeBytes, offset, kind, stream);
};

hipError_t hipCtxCreate(hipCtx_t * ctx, unsigned int flags, hipDevice_t device) {
	return ((__hipCtxCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxCreate])(ctx, flags, device);
};

hipError_t hipLaunchCooperativeKernel(const void * f, dim3 gridDim, dim3 blockDimX, void ** kernelParams, unsigned int sharedMemBytes, hipStream_t stream) {
	return ((__hipLaunchCooperativeKernel_t)hip_api_table.api_ptr[HIP_API_ID_hipLaunchCooperativeKernel])(f, gridDim, blockDimX, kernelParams, sharedMemBytes, stream);
};

hipError_t hipExtStreamGetCUMask(hipStream_t stream, uint32_t cuMaskSize, uint32_t * cuMask) {
	return ((__hipExtStreamGetCUMask_t)hip_api_table.api_ptr[HIP_API_ID_hipExtStreamGetCUMask])(stream, cuMaskSize, cuMask);
};

hipError_t hipGraphExecDestroy(hipGraphExec_t graphExec) {
	return ((__hipGraphExecDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecDestroy])(graphExec);
};

hipError_t hipDrvGetErrorString(hipError_t hipError, const char ** errorString) {
	return ((__hipDrvGetErrorString_t)hip_api_table.api_ptr[HIP_API_ID_hipDrvGetErrorString])(hipError, errorString);
};

hipError_t hipInit(unsigned int flags) {
	return ((__hipInit_t)hip_api_table.api_ptr[HIP_API_ID_hipInit])(flags);
};

hipError_t hipBindTexture2D(size_t * offset, const textureReference * tex, const void * devPtr, const hipChannelFormatDesc * desc, size_t width, size_t height, size_t pitch) {
	return ((__hipBindTexture2D_t)hip_api_table.api_ptr[HIP_API_ID_hipBindTexture2D])(offset, tex, devPtr, desc, width, height, pitch);
};

hipError_t hipExtGetLinkTypeAndHopCount(int device1, int device2, uint32_t * linktype, uint32_t * hopcount) {
	return ((__hipExtGetLinkTypeAndHopCount_t)hip_api_table.api_ptr[HIP_API_ID_hipExtGetLinkTypeAndHopCount])(device1, device2, linktype, hopcount);
};

hipError_t hipGetTextureObjectResourceViewDesc(struct hipResourceViewDesc * pResViewDesc, hipTextureObject_t textureObject) {
	return ((__hipGetTextureObjectResourceViewDesc_t)hip_api_table.api_ptr[HIP_API_ID_hipGetTextureObjectResourceViewDesc])(pResViewDesc, textureObject);
};

hipError_t hipMemCreate(hipMemGenericAllocationHandle_t * handle, size_t size, const hipMemAllocationProp * prop, unsigned long long flags) {
	return ((__hipMemCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipMemCreate])(handle, size, prop, flags);
};

hipError_t hipMemsetD8Async(hipDeviceptr_t dest, unsigned char value, size_t count, hipStream_t stream) {
	return ((__hipMemsetD8Async_t)hip_api_table.api_ptr[HIP_API_ID_hipMemsetD8Async])(dest, value, count, stream);
};

hipError_t hipLaunchHostFunc(hipStream_t stream, hipHostFn_t fn, void * userData) {
	return ((__hipLaunchHostFunc_t)hip_api_table.api_ptr[HIP_API_ID_hipLaunchHostFunc])(stream, fn, userData);
};

hipError_t hipGraphGetEdges(hipGraph_t graph, hipGraphNode_t * from, hipGraphNode_t * to, size_t * numEdges) {
	return ((__hipGraphGetEdges_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphGetEdges])(graph, from, to, numEdges);
};

hipError_t hipMemPoolDestroy(hipMemPool_t mem_pool) {
	return ((__hipMemPoolDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolDestroy])(mem_pool);
};

hipError_t hipGraphKernelNodeGetParams(hipGraphNode_t node, hipKernelNodeParams * pNodeParams) {
	return ((__hipGraphKernelNodeGetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphKernelNodeGetParams])(node, pNodeParams);
};

hipError_t hipDrvPointerGetAttributes(unsigned int numAttributes, hipPointer_attribute * attributes, void ** data, hipDeviceptr_t ptr) {
	return ((__hipDrvPointerGetAttributes_t)hip_api_table.api_ptr[HIP_API_ID_hipDrvPointerGetAttributes])(numAttributes, attributes, data, ptr);
};

hipError_t hipFuncSetAttribute(const void * func, hipFuncAttribute attr, int value) {
	return ((__hipFuncSetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipFuncSetAttribute])(func, attr, value);
};

hipError_t hipGraphAddDependencies(hipGraph_t graph, const hipGraphNode_t * from, const hipGraphNode_t * to, size_t numDependencies) {
	return ((__hipGraphAddDependencies_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddDependencies])(graph, from, to, numDependencies);
};

hipError_t hipStreamWriteValue64(hipStream_t stream, void * ptr, uint64_t value, unsigned int flags) {
	return ((__hipStreamWriteValue64_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamWriteValue64])(stream, ptr, value, flags);
};

hipError_t hipCreateSurfaceObject(hipSurfaceObject_t* pSurfObject, const hipResourceDesc* pResDesc) {
	return ((__hipCreateSurfaceObject_t)hip_api_table.api_ptr[HIP_API_ID_hipCreateSurfaceObject])(pSurfObject, pResDesc);
};

hipError_t hipGetTextureObjectTextureDesc(hipTextureDesc* pTexDesc, hipTextureObject_t textureObject) {
	return ((__hipGetTextureObjectTextureDesc_t)hip_api_table.api_ptr[HIP_API_ID_hipGetTextureObjectTextureDesc])(pTexDesc, textureObject);
};

hipError_t hipMemUnmap(void * ptr, size_t size) {
	return ((__hipMemUnmap_t)hip_api_table.api_ptr[HIP_API_ID_hipMemUnmap])(ptr, size);
};

hipError_t hipGraphChildGraphNodeGetGraph(hipGraphNode_t node, hipGraph_t * pGraph) {
	return ((__hipGraphChildGraphNodeGetGraph_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphChildGraphNodeGetGraph])(node, pGraph);
};

hipError_t hipStreamCreateWithFlags(hipStream_t * stream, unsigned int flags) {
	return ((__hipStreamCreateWithFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamCreateWithFlags])(stream, flags);
};

hipError_t hipMemPoolCreate(hipMemPool_t * mem_pool, const hipMemPoolProps * pool_props) {
	return ((__hipMemPoolCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolCreate])(mem_pool, pool_props);
};

hipError_t hipLaunchCooperativeKernelMultiDevice(hipLaunchParams * launchParamsList, int numDevices, unsigned int flags) {
	return ((__hipLaunchCooperativeKernelMultiDevice_t)hip_api_table.api_ptr[HIP_API_ID_hipLaunchCooperativeKernelMultiDevice])(launchParamsList, numDevices, flags);
};

hipError_t hipTexRefSetFilterMode(textureReference* texRef, enum hipTextureFilterMode fm) {
	return ((__hipTexRefSetFilterMode_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetFilterMode])(texRef, fm);
};

hipError_t hipDeviceSetGraphMemAttribute(int device, hipGraphMemAttributeType attr, void * value) {
	return ((__hipDeviceSetGraphMemAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceSetGraphMemAttribute])(device, attr, value);
};

hipError_t hipGraphExecMemcpyNodeSetParams1D(hipGraphExec_t hGraphExec, hipGraphNode_t node, void * dst, const void * src, size_t count, hipMemcpyKind kind) {
	return ((__hipGraphExecMemcpyNodeSetParams1D_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecMemcpyNodeSetParams1D])(hGraphExec, node, dst, src, count, kind);
};

hipError_t hipGraphExecKernelNodeSetParams(hipGraphExec_t hGraphExec, hipGraphNode_t node, const hipKernelNodeParams * pNodeParams) {
	return ((__hipGraphExecKernelNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecKernelNodeSetParams])(hGraphExec, node, pNodeParams);
};

hipError_t hipGraphInstantiate(hipGraphExec_t * pGraphExec, hipGraph_t graph, hipGraphNode_t * pErrorNode, char * pLogBuffer, size_t bufferSize) {
	return ((__hipGraphInstantiate_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphInstantiate])(pGraphExec, graph, pErrorNode, pLogBuffer, bufferSize);
};

hipError_t hipGraphExecExternalSemaphoresSignalNodeSetParams(hipGraphExec_t hGraphExec, hipGraphNode_t hNode, const hipExternalSemaphoreSignalNodeParams * nodeParams) {
	return ((__hipGraphExecExternalSemaphoresSignalNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecExternalSemaphoresSignalNodeSetParams])(hGraphExec, hNode, nodeParams);
};

hipError_t hipCreateTextureObject(hipTextureObject_t* pTexObject, const hipResourceDesc* pResDesc, const hipTextureDesc* pTexDesc, const struct hipResourceViewDesc * pResViewDesc) {
	return ((__hipCreateTextureObject_t)hip_api_table.api_ptr[HIP_API_ID_hipCreateTextureObject])(pTexObject, pResDesc, pTexDesc, pResViewDesc);
};

hipError_t hipEventQuery(hipEvent_t event) {
	return ((__hipEventQuery_t)hip_api_table.api_ptr[HIP_API_ID_hipEventQuery])(event);
};

hipError_t hipCtxPushCurrent(hipCtx_t ctx) {
	return ((__hipCtxPushCurrent_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxPushCurrent])(ctx);
};

hipError_t hipGraphGetRootNodes(hipGraph_t graph, hipGraphNode_t * pRootNodes, size_t * pNumRootNodes) {
	return ((__hipGraphGetRootNodes_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphGetRootNodes])(graph, pRootNodes, pNumRootNodes);
};

const char * hipGetErrorString(hipError_t hipError) {
	return ((__hipGetErrorString_t)hip_api_table.api_ptr[HIP_API_ID_hipGetErrorString])(hipError);
};

hipError_t hipMemAddressFree(void * devPtr, size_t size) {
	return ((__hipMemAddressFree_t)hip_api_table.api_ptr[HIP_API_ID_hipMemAddressFree])(devPtr, size);
};

hipError_t hipDeviceSynchronize() {
	return ((__hipDeviceSynchronize_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceSynchronize])();
};

hipError_t hipCtxGetFlags(unsigned int * flags) {
	return ((__hipCtxGetFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxGetFlags])(flags);
};

hipError_t hipTexRefGetArray(hipArray_t* pArray, const textureReference* texRef) {
	return ((__hipTexRefGetArray_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetArray])(pArray, texRef);
};

hipError_t hipMemGetAllocationGranularity(size_t * granularity, const hipMemAllocationProp * prop, hipMemAllocationGranularity_flags option) {
	return ((__hipMemGetAllocationGranularity_t)hip_api_table.api_ptr[HIP_API_ID_hipMemGetAllocationGranularity])(granularity, prop, option);
};

hipError_t hipProfilerStop() {
	return ((__hipProfilerStop_t)hip_api_table.api_ptr[HIP_API_ID_hipProfilerStop])();
};

hipError_t hipTexRefSetArray(textureReference* tex, hipArray_const_t array, unsigned int flags) {
	return ((__hipTexRefSetArray_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetArray])(tex, array, flags);
};

hipError_t hipEventDestroy(hipEvent_t event) {
	return ((__hipEventDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipEventDestroy])(event);
};

hipError_t hipDeviceSetCacheConfig(hipFuncCache_t cacheConfig) {
	return ((__hipDeviceSetCacheConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceSetCacheConfig])(cacheConfig);
};

hipError_t hipLaunchByPtr(const void * func) {
	return ((__hipLaunchByPtr_t)hip_api_table.api_ptr[HIP_API_ID_hipLaunchByPtr])(func);
};

hipError_t hipModuleLaunchCooperativeKernelMultiDevice(hipFunctionLaunchParams * launchParamsList, unsigned int numDevices, unsigned int flags) {
	return ((__hipModuleLaunchCooperativeKernelMultiDevice_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleLaunchCooperativeKernelMultiDevice])(launchParamsList, numDevices, flags);
};

hipError_t hipTexRefSetAddressMode(textureReference* texRef, int dim, enum hipTextureAddressMode am) {
	return ((__hipTexRefSetAddressMode_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetAddressMode])(texRef, dim, am);
};

hipError_t hipModuleLoadData(hipModule_t * module, const void * image) {
	return ((__hipModuleLoadData_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleLoadData])(module, image);
};

hipError_t hipDrvMemcpy2DUnaligned(const hip_Memcpy2D * pCopy) {
	return ((__hipDrvMemcpy2DUnaligned_t)hip_api_table.api_ptr[HIP_API_ID_hipDrvMemcpy2DUnaligned])(pCopy);
};

hipError_t hipGraphExecChildGraphNodeSetParams(hipGraphExec_t hGraphExec, hipGraphNode_t node, hipGraph_t childGraph) {
	return ((__hipGraphExecChildGraphNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecChildGraphNodeSetParams])(hGraphExec, node, childGraph);
};

hipError_t hipPointerGetAttributes(hipPointerAttribute_t * attributes, const void * ptr) {
	return ((__hipPointerGetAttributes_t)hip_api_table.api_ptr[HIP_API_ID_hipPointerGetAttributes])(attributes, ptr);
};

hipError_t hipMemcpyDtoHAsync(void * dst, hipDeviceptr_t src, size_t sizeBytes, hipStream_t stream) {
	return ((__hipMemcpyDtoHAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyDtoHAsync])(dst, src, sizeBytes, stream);
};

hipError_t hipGraphAddEventRecordNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, hipEvent_t event) {
	return ((__hipGraphAddEventRecordNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddEventRecordNode])(pGraphNode, graph, pDependencies, numDependencies, event);
};

hipError_t hipGraphAddExternalSemaphoresSignalNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, const hipExternalSemaphoreSignalNodeParams * nodeParams) {
	return ((__hipGraphAddExternalSemaphoresSignalNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddExternalSemaphoresSignalNode])(pGraphNode, graph, pDependencies, numDependencies, nodeParams);
};

hipError_t hipGraphRetainUserObject(hipGraph_t graph, hipUserObject_t object, unsigned int count, unsigned int flags) {
	return ((__hipGraphRetainUserObject_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphRetainUserObject])(graph, object, count, flags);
};

hipError_t hipSetupArgument(const void * arg, size_t size, size_t offset) {
	return ((__hipSetupArgument_t)hip_api_table.api_ptr[HIP_API_ID_hipSetupArgument])(arg, size, offset);
};

hipError_t hipMemAllocPitch(hipDeviceptr_t * dptr, size_t* pitch, size_t widthInBytes, size_t height, unsigned int elementSizeBytes) {
	return ((__hipMemAllocPitch_t)hip_api_table.api_ptr[HIP_API_ID_hipMemAllocPitch])(dptr, pitch, widthInBytes, height, elementSizeBytes);
};

hipError_t hipGraphEventWaitNodeGetEvent(hipGraphNode_t node, hipEvent_t * event_out) {
	return ((__hipGraphEventWaitNodeGetEvent_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphEventWaitNodeGetEvent])(node, event_out);
};

hipError_t hipMemcpy2DToArray(hipArray_t dst, size_t wOffset, size_t hOffset, const void * src, size_t spitch, size_t width, size_t height, hipMemcpyKind kind) {
	return ((__hipMemcpy2DToArray_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy2DToArray])(dst, wOffset, hOffset, src, spitch, width, height, kind);
};

hipError_t hipMemcpyPeerAsync(void * dst, int dstDeviceId, const void * src, int srcDevice, size_t sizeBytes, hipStream_t stream) {
	return ((__hipMemcpyPeerAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyPeerAsync])(dst, dstDeviceId, src, srcDevice, sizeBytes, stream);
};

hipError_t hipTexObjectCreate(hipTextureObject_t* pTexObject, const HIP_RESOURCE_DESC* pResDesc, const HIP_TEXTURE_DESC* pTexDesc, const HIP_RESOURCE_VIEW_DESC* pResViewDesc) {
	return ((__hipTexObjectCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipTexObjectCreate])(pTexObject, pResDesc, pTexDesc, pResViewDesc);
};

hipError_t hipDeviceGetLimit(size_t * pValue, enum hipLimit_t limit) {
	return ((__hipDeviceGetLimit_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetLimit])(pValue, limit);
};

hipError_t hipExtMallocWithFlags(void ** ptr, size_t sizeBytes, unsigned int flags) {
	return ((__hipExtMallocWithFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipExtMallocWithFlags])(ptr, sizeBytes, flags);
};

const char * hipGetErrorName(hipError_t hip_error) {
	return ((__hipGetErrorName_t)hip_api_table.api_ptr[HIP_API_ID_hipGetErrorName])(hip_error);
};

hipError_t hipMemcpy3D(const struct hipMemcpy3DParms * p) {
	return ((__hipMemcpy3D_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy3D])(p);
};

hipError_t hipGraphMemcpyNodeSetParamsFromSymbol(hipGraphNode_t node, void * dst, const void * symbol, size_t count, size_t offset, hipMemcpyKind kind) {
	return ((__hipGraphMemcpyNodeSetParamsFromSymbol_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphMemcpyNodeSetParamsFromSymbol])(node, dst, symbol, count, offset, kind);
};

hipError_t hipMemRangeGetAttributes(void ** data, size_t * data_sizes, hipMemRangeAttribute * attributes, size_t num_attributes, const void * dev_ptr, size_t count) {
	return ((__hipMemRangeGetAttributes_t)hip_api_table.api_ptr[HIP_API_ID_hipMemRangeGetAttributes])(data, data_sizes, attributes, num_attributes, dev_ptr, count);
};

hipError_t hipGraphDebugDotPrint(hipGraph_t graph, const char * path, unsigned int flags) {
	return ((__hipGraphDebugDotPrint_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphDebugDotPrint])(graph, path, flags);
};

hipError_t hipGraphExternalSemaphoresWaitNodeGetParams(hipGraphNode_t hNode, hipExternalSemaphoreWaitNodeParams * params_out) {
	return ((__hipGraphExternalSemaphoresWaitNodeGetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExternalSemaphoresWaitNodeGetParams])(hNode, params_out);
};

hipError_t hipMemset(void * dst, int value, size_t sizeBytes) {
	return ((__hipMemset_t)hip_api_table.api_ptr[HIP_API_ID_hipMemset])(dst, value, sizeBytes);
};

hipError_t hipGraphAddHostNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, const hipHostNodeParams* pNodeParams) {
	return ((__hipGraphAddHostNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddHostNode])(pGraphNode, graph, pDependencies, numDependencies, pNodeParams);
};

hipError_t hipGraphAddMemcpyNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, const hipMemcpy3DParms* pCopyParams) {
	return ((__hipGraphAddMemcpyNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddMemcpyNode])(pGraphNode, graph, pDependencies, numDependencies, pCopyParams);
};

hipError_t hipGraphHostNodeGetParams(hipGraphNode_t node, hipHostNodeParams * pNodeParams) {
	return ((__hipGraphHostNodeGetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphHostNodeGetParams])(node, pNodeParams);
};

hipError_t hipDeviceGetByPCIBusId(int * device, const char * pciBusId) {
	return ((__hipDeviceGetByPCIBusId_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetByPCIBusId])(device, pciBusId);
};

hipError_t hipMemcpyDtoD(hipDeviceptr_t dst, hipDeviceptr_t src, size_t sizeBytes) {
	return ((__hipMemcpyDtoD_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyDtoD])(dst, src, sizeBytes);
};

hipError_t hipIpcGetEventHandle(hipIpcEventHandle_t * handle, hipEvent_t event) {
	return ((__hipIpcGetEventHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipIpcGetEventHandle])(handle, event);
};

hipError_t hipGraphKernelNodeSetParams(hipGraphNode_t node, const hipKernelNodeParams * pNodeParams) {
	return ((__hipGraphKernelNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphKernelNodeSetParams])(node, pNodeParams);
};

hipError_t hipModuleGetFunction(hipFunction_t * function, hipModule_t module, const char * kname) {
	return ((__hipModuleGetFunction_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleGetFunction])(function, module, kname);
};

hipError_t hipMemcpyAtoH(void * dst, hipArray_t srcArray, size_t srcOffset, size_t count) {
	return ((__hipMemcpyAtoH_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyAtoH])(dst, srcArray, srcOffset, count);
};

hipError_t hipDeviceEnablePeerAccess(int peerDeviceId, unsigned int flags) {
	return ((__hipDeviceEnablePeerAccess_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceEnablePeerAccess])(peerDeviceId, flags);
};

hipError_t hipMemRetainAllocationHandle(hipMemGenericAllocationHandle_t * handle, void * addr) {
	return ((__hipMemRetainAllocationHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipMemRetainAllocationHandle])(handle, addr);
};

hipError_t hipTexRefGetMipMappedArray(hipMipmappedArray_t* pArray, const textureReference* texRef) {
	return ((__hipTexRefGetMipMappedArray_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetMipMappedArray])(pArray, texRef);
};

hipError_t hipTexRefGetMipmapLevelBias(float * pbias, const textureReference* texRef) {
	return ((__hipTexRefGetMipmapLevelBias_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetMipmapLevelBias])(pbias, texRef);
};

hipError_t hipBindTexture(size_t * offset, const textureReference* tex, const void * devPtr, const hipChannelFormatDesc * desc, size_t size) {
	return ((__hipBindTexture_t)hip_api_table.api_ptr[HIP_API_ID_hipBindTexture])(offset, tex, devPtr, desc, size);
};

hipError_t hipGraphAddChildGraphNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, hipGraph_t childGraph) {
	return ((__hipGraphAddChildGraphNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddChildGraphNode])(pGraphNode, graph, pDependencies, numDependencies, childGraph);
};

hipError_t hipDeviceSetLimit(enum hipLimit_t limit, size_t value) {
	return ((__hipDeviceSetLimit_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceSetLimit])(limit, value);
};

hipError_t hipGetChannelDesc(hipChannelFormatDesc * desc, hipArray_const_t array) {
	return ((__hipGetChannelDesc_t)hip_api_table.api_ptr[HIP_API_ID_hipGetChannelDesc])(desc, array);
};

hipError_t hipGraphicsUnregisterResource(hipGraphicsResource_t resource) {
	return ((__hipGraphicsUnregisterResource_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphicsUnregisterResource])(resource);
};

hipError_t hipGraphRemoveDependencies(hipGraph_t graph, const hipGraphNode_t * from, const hipGraphNode_t * to, size_t numDependencies) {
	return ((__hipGraphRemoveDependencies_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphRemoveDependencies])(graph, from, to, numDependencies);
};

hipError_t hipTexRefSetBorderColor(textureReference* texRef, float * pBorderColor) {
	return ((__hipTexRefSetBorderColor_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetBorderColor])(texRef, pBorderColor);
};

hipError_t hipDevicePrimaryCtxGetState(hipDevice_t dev, unsigned int * flags, int * active) {
	return ((__hipDevicePrimaryCtxGetState_t)hip_api_table.api_ptr[HIP_API_ID_hipDevicePrimaryCtxGetState])(dev, flags, active);
};

hipError_t hipMalloc3D(hipPitchedPtr* pitchedDevPtr, hipExtent extent) {
	return ((__hipMalloc3D_t)hip_api_table.api_ptr[HIP_API_ID_hipMalloc3D])(pitchedDevPtr, extent);
};

hipError_t hipTexRefGetMipmapLevelClamp(float * pminMipmapLevelClamp, float * pmaxMipmapLevelClamp, const textureReference* texRef) {
	return ((__hipTexRefGetMipmapLevelClamp_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetMipmapLevelClamp])(pminMipmapLevelClamp, pmaxMipmapLevelClamp, texRef);
};

hipError_t hipModuleLaunchKernel(hipFunction_t f, unsigned int gridDimX, unsigned int gridDimY, unsigned int gridDimZ, unsigned int blockDimX, unsigned int blockDimY, unsigned int blockDimZ, unsigned int sharedMemBytes, hipStream_t stream, void ** kernelParams, void ** extra) {
	return ((__hipModuleLaunchKernel_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleLaunchKernel])(f, gridDimX, gridDimY, gridDimZ, blockDimX, blockDimY, blockDimZ, sharedMemBytes, stream, kernelParams, extra);
};

const char * hipKernelNameRefByPtr(const void * hostFunction, hipStream_t stream) {
	return ((__hipKernelNameRefByPtr_t)hip_api_table.api_ptr[HIP_API_ID_hipKernelNameRefByPtr])(hostFunction, stream);
};

hipError_t hipDeviceSetSharedMemConfig(hipSharedMemConfig config) {
	return ((__hipDeviceSetSharedMemConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceSetSharedMemConfig])(config);
};

hipError_t hipMemcpyToSymbolAsync(const void * symbol, const void * src, size_t sizeBytes, size_t offset, hipMemcpyKind kind, hipStream_t stream) {
	return ((__hipMemcpyToSymbolAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyToSymbolAsync])(symbol, src, sizeBytes, offset, kind, stream);
};

hipError_t hipHostGetDevicePointer(void ** devPtr, void * hstPtr, unsigned int flags) {
	return ((__hipHostGetDevicePointer_t)hip_api_table.api_ptr[HIP_API_ID_hipHostGetDevicePointer])(devPtr, hstPtr, flags);
};

hipError_t hipGraphReleaseUserObject(hipGraph_t graph, hipUserObject_t object, unsigned int count) {
	return ((__hipGraphReleaseUserObject_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphReleaseUserObject])(graph, object, count);
};

hipError_t hipDeviceGraphMemTrim(int device) {
	return ((__hipDeviceGraphMemTrim_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGraphMemTrim])(device);
};

hipError_t hipDeviceGetStreamPriorityRange(int * leastPriority, int * greatestPriority) {
	return ((__hipDeviceGetStreamPriorityRange_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetStreamPriorityRange])(leastPriority, greatestPriority);
};

hipError_t hipPointerGetAttribute(void * data, hipPointer_attribute attribute, hipDeviceptr_t ptr) {
	return ((__hipPointerGetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipPointerGetAttribute])(data, attribute, ptr);
};

hipError_t hipMemPoolSetAccess(hipMemPool_t mem_pool, const hipMemAccessDesc * desc_list, size_t count) {
	return ((__hipMemPoolSetAccess_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolSetAccess])(mem_pool, desc_list, count);
};

hipError_t hipGraphExecExternalSemaphoresWaitNodeSetParams(hipGraphExec_t hGraphExec, hipGraphNode_t hNode, const hipExternalSemaphoreWaitNodeParams * nodeParams) {
	return ((__hipGraphExecExternalSemaphoresWaitNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecExternalSemaphoresWaitNodeSetParams])(hGraphExec, hNode, nodeParams);
};

hipError_t hipMemcpy(void * dst, const void * src, size_t sizeBytes, hipMemcpyKind kind) {
	return ((__hipMemcpy_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy])(dst, src, sizeBytes, kind);
};

hipError_t hipDeviceDisablePeerAccess(int peerDeviceId) {
	return ((__hipDeviceDisablePeerAccess_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceDisablePeerAccess])(peerDeviceId);
};

hipError_t hipGraphKernelNodeSetAttribute(hipGraphNode_t hNode, hipKernelNodeAttrID attr, const hipKernelNodeAttrValue * value) {
	return ((__hipGraphKernelNodeSetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphKernelNodeSetAttribute])(hNode, attr, value);
};

hipError_t hipGraphAddMemcpyNode1D(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, void * dst, const void * src, size_t count, hipMemcpyKind kind) {
	return ((__hipGraphAddMemcpyNode1D_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddMemcpyNode1D])(pGraphNode, graph, pDependencies, numDependencies, dst, src, count, kind);
};

hipError_t hipGraphExecEventRecordNodeSetEvent(hipGraphExec_t hGraphExec, hipGraphNode_t hNode, hipEvent_t event) {
	return ((__hipGraphExecEventRecordNodeSetEvent_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecEventRecordNodeSetEvent])(hGraphExec, hNode, event);
};

hipError_t hipGraphicsUnmapResources(int count, hipGraphicsResource_t * resources, hipStream_t stream) {
	return ((__hipGraphicsUnmapResources_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphicsUnmapResources])(count, resources, stream);
};

hipError_t hipGraphAddExternalSemaphoresWaitNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, const hipExternalSemaphoreWaitNodeParams * nodeParams) {
	return ((__hipGraphAddExternalSemaphoresWaitNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddExternalSemaphoresWaitNode])(pGraphNode, graph, pDependencies, numDependencies, nodeParams);
};

hipError_t hipDrvGraphAddMemcpyNode(hipGraphNode_t * phGraphNode, hipGraph_t hGraph, const hipGraphNode_t * dependencies, size_t numDependencies, const HIP_MEMCPY3D * copyParams, hipCtx_t ctx) {
	return ((__hipDrvGraphAddMemcpyNode_t)hip_api_table.api_ptr[HIP_API_ID_hipDrvGraphAddMemcpyNode])(phGraphNode, hGraph, dependencies, numDependencies, copyParams, ctx);
};

hipError_t hipEventElapsedTime(float * ms, hipEvent_t start, hipEvent_t stop) {
	return ((__hipEventElapsedTime_t)hip_api_table.api_ptr[HIP_API_ID_hipEventElapsedTime])(ms, start, stop);
};

hipError_t hipMemcpy3DAsync(const struct hipMemcpy3DParms * p, hipStream_t stream) {
	return ((__hipMemcpy3DAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy3DAsync])(p, stream);
};

hipError_t hipTexRefGetMaxAnisotropy(int * pmaxAnsio, const textureReference* texRef) {
	return ((__hipTexRefGetMaxAnisotropy_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetMaxAnisotropy])(pmaxAnsio, texRef);
};

hipError_t hipGraphNodeGetDependentNodes(hipGraphNode_t node, hipGraphNode_t * pDependentNodes, size_t * pNumDependentNodes) {
	return ((__hipGraphNodeGetDependentNodes_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphNodeGetDependentNodes])(node, pDependentNodes, pNumDependentNodes);
};

hipError_t hipMemPoolGetAttribute(hipMemPool_t mem_pool, hipMemPoolAttr attr, void * value) {
	return ((__hipMemPoolGetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolGetAttribute])(mem_pool, attr, value);
};

hipError_t hipStreamGetDevice(hipStream_t stream, hipDevice_t * device) {
	return ((__hipStreamGetDevice_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamGetDevice])(stream, device);
};

hipError_t hipGetTextureObjectResourceDesc(hipResourceDesc* pResDesc, hipTextureObject_t textureObject) {
	return ((__hipGetTextureObjectResourceDesc_t)hip_api_table.api_ptr[HIP_API_ID_hipGetTextureObjectResourceDesc])(pResDesc, textureObject);
};

hipError_t hipTexRefGetFlags(unsigned int * pFlags, const textureReference* texRef) {
	return ((__hipTexRefGetFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetFlags])(pFlags, texRef);
};

hipError_t hipChooseDeviceR0600(int * device, const hipDeviceProp_tR0600 * prop) {
	return ((__hipChooseDeviceR0600_t)hip_api_table.api_ptr[HIP_API_ID_hipChooseDeviceR0600])(device, prop);
};

hipError_t hipSignalExternalSemaphoresAsync(const hipExternalSemaphore_t * extSemArray, const hipExternalSemaphoreSignalParams * paramsArray, unsigned int numExtSems, hipStream_t stream) {
	return ((__hipSignalExternalSemaphoresAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipSignalExternalSemaphoresAsync])(extSemArray, paramsArray, numExtSems, stream);
};

hipError_t hipDeviceCanAccessPeer(int * canAccessPeer, int deviceId, int peerDeviceId) {
	return ((__hipDeviceCanAccessPeer_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceCanAccessPeer])(canAccessPeer, deviceId, peerDeviceId);
};

hipError_t hipDevicePrimaryCtxRetain(hipCtx_t * pctx, hipDevice_t dev) {
	return ((__hipDevicePrimaryCtxRetain_t)hip_api_table.api_ptr[HIP_API_ID_hipDevicePrimaryCtxRetain])(pctx, dev);
};

hipError_t hipCtxDisablePeerAccess(hipCtx_t peerCtx) {
	return ((__hipCtxDisablePeerAccess_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxDisablePeerAccess])(peerCtx);
};

hipError_t hipStreamGetPriority(hipStream_t stream, int * priority) {
	return ((__hipStreamGetPriority_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamGetPriority])(stream, priority);
};

hipError_t hipEventCreate(hipEvent_t * event) {
	return ((__hipEventCreate_t)hip_api_table.api_ptr[HIP_API_ID_hipEventCreate])(event);
};

hipError_t hipGetLastError() {
	return ((__hipGetLastError_t)hip_api_table.api_ptr[HIP_API_ID_hipGetLastError])();
};

hipError_t hipDeviceComputeCapability(int * major, int * minor, hipDevice_t device) {
	return ((__hipDeviceComputeCapability_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceComputeCapability])(major, minor, device);
};

hipError_t hipGetDevicePropertiesR0600(hipDeviceProp_tR0600 * prop, int deviceId) {
	return ((__hipGetDevicePropertiesR0600_t)hip_api_table.api_ptr[HIP_API_ID_hipGetDevicePropertiesR0600])(prop, deviceId);
};

hipError_t hipOccupancyMaxPotentialBlockSize(int * gridSize, int * blockSize, const void * f, size_t dynSharedMemPerBlk, int blockSizeLimit) {
	return ((__hipOccupancyMaxPotentialBlockSize_t)hip_api_table.api_ptr[HIP_API_ID_hipOccupancyMaxPotentialBlockSize])(gridSize, blockSize, f, dynSharedMemPerBlk, blockSizeLimit);
};

hipError_t hipGetTextureAlignmentOffset(size_t * offset, const textureReference* texRef) {
	return ((__hipGetTextureAlignmentOffset_t)hip_api_table.api_ptr[HIP_API_ID_hipGetTextureAlignmentOffset])(offset, texRef);
};

hipError_t hipIpcOpenMemHandle(void ** devPtr, hipIpcMemHandle_t handle, unsigned int flags) {
	return ((__hipIpcOpenMemHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipIpcOpenMemHandle])(devPtr, handle, flags);
};

hipError_t hipGraphNodeFindInClone(hipGraphNode_t * pNode, hipGraphNode_t originalNode, hipGraph_t clonedGraph) {
	return ((__hipGraphNodeFindInClone_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphNodeFindInClone])(pNode, originalNode, clonedGraph);
};

hipError_t hipDevicePrimaryCtxRelease(hipDevice_t dev) {
	return ((__hipDevicePrimaryCtxRelease_t)hip_api_table.api_ptr[HIP_API_ID_hipDevicePrimaryCtxRelease])(dev);
};

hipError_t hipCtxSetCurrent(hipCtx_t ctx) {
	return ((__hipCtxSetCurrent_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxSetCurrent])(ctx);
};

hipError_t hipGraphExecMemcpyNodeSetParamsFromSymbol(hipGraphExec_t hGraphExec, hipGraphNode_t node, void * dst, const void * symbol, size_t count, size_t offset, hipMemcpyKind kind) {
	return ((__hipGraphExecMemcpyNodeSetParamsFromSymbol_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecMemcpyNodeSetParamsFromSymbol])(hGraphExec, node, dst, symbol, count, offset, kind);
};

hipError_t hipCtxSetCacheConfig(hipFuncCache_t cacheConfig) {
	return ((__hipCtxSetCacheConfig_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxSetCacheConfig])(cacheConfig);
};

hipError_t hipMemMapArrayAsync(hipArrayMapInfo * mapInfoList, unsigned int count, hipStream_t stream) {
	return ((__hipMemMapArrayAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemMapArrayAsync])(mapInfoList, count, stream);
};

hipError_t hipImportExternalMemory(hipExternalMemory_t * extMem_out, const hipExternalMemoryHandleDesc * memHandleDesc) {
	return ((__hipImportExternalMemory_t)hip_api_table.api_ptr[HIP_API_ID_hipImportExternalMemory])(extMem_out, memHandleDesc);
};

hipError_t hipGraphExecEventWaitNodeSetEvent(hipGraphExec_t hGraphExec, hipGraphNode_t hNode, hipEvent_t event) {
	return ((__hipGraphExecEventWaitNodeSetEvent_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecEventWaitNodeSetEvent])(hGraphExec, hNode, event);
};

hipError_t hipStreamBeginCapture(hipStream_t stream, hipStreamCaptureMode mode) {
	return ((__hipStreamBeginCapture_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamBeginCapture])(stream, mode);
};

hipError_t hipIpcGetMemHandle(hipIpcMemHandle_t * handle, void * devPtr) {
	return ((__hipIpcGetMemHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipIpcGetMemHandle])(handle, devPtr);
};

hipError_t hipWaitExternalSemaphoresAsync(const hipExternalSemaphore_t * extSemArray, const hipExternalSemaphoreWaitParams * paramsArray, unsigned int numExtSems, hipStream_t stream) {
	return ((__hipWaitExternalSemaphoresAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipWaitExternalSemaphoresAsync])(extSemArray, paramsArray, numExtSems, stream);
};

hipError_t hipTexRefGetMipmapFilterMode(enum hipTextureFilterMode * pfm, const textureReference* texRef) {
	return ((__hipTexRefGetMipmapFilterMode_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefGetMipmapFilterMode])(pfm, texRef);
};

hipError_t hipMemPoolGetAccess(hipMemAccessFlags * flags, hipMemPool_t mem_pool, hipMemLocation * location) {
	return ((__hipMemPoolGetAccess_t)hip_api_table.api_ptr[HIP_API_ID_hipMemPoolGetAccess])(flags, mem_pool, location);
};

hipError_t hipDrvGraphAddMemsetNode(hipGraphNode_t * phGraphNode, hipGraph_t hGraph, const hipGraphNode_t * dependencies, size_t numDependencies, const HIP_MEMSET_NODE_PARAMS * memsetParams, hipCtx_t ctx) {
	return ((__hipDrvGraphAddMemsetNode_t)hip_api_table.api_ptr[HIP_API_ID_hipDrvGraphAddMemsetNode])(phGraphNode, hGraph, dependencies, numDependencies, memsetParams, ctx);
};

hipError_t hipMemset3D(hipPitchedPtr pitchedDevPtr, int value, hipExtent extent) {
	return ((__hipMemset3D_t)hip_api_table.api_ptr[HIP_API_ID_hipMemset3D])(pitchedDevPtr, value, extent);
};

hipError_t hipDrvMemcpy3D(const HIP_MEMCPY3D * pCopy) {
	return ((__hipDrvMemcpy3D_t)hip_api_table.api_ptr[HIP_API_ID_hipDrvMemcpy3D])(pCopy);
};

hipError_t hipMemcpy2DFromArrayAsync(void * dst, size_t dpitch, hipArray_const_t src, size_t wOffset, size_t hOffset, size_t width, size_t height, hipMemcpyKind kind, hipStream_t stream) {
	return ((__hipMemcpy2DFromArrayAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpy2DFromArrayAsync])(dst, dpitch, src, wOffset, hOffset, width, height, kind, stream);
};

hipError_t hipExtLaunchMultiKernelMultiDevice(hipLaunchParams * launchParamsList, int numDevices, unsigned int flags) {
	return ((__hipExtLaunchMultiKernelMultiDevice_t)hip_api_table.api_ptr[HIP_API_ID_hipExtLaunchMultiKernelMultiDevice])(launchParamsList, numDevices, flags);
};

hipError_t hipStreamWaitValue64(hipStream_t stream, void * ptr, uint64_t value, unsigned int flags, uint64_t mask) {
	return ((__hipStreamWaitValue64_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamWaitValue64])(stream, ptr, value, flags, mask);
};

hipError_t hipModuleGetTexRef(textureReference** texRef, hipModule_t hmod, const char * name) {
	return ((__hipModuleGetTexRef_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleGetTexRef])(texRef, hmod, name);
};

hipError_t hipMemcpyDtoDAsync(hipDeviceptr_t dst, hipDeviceptr_t src, size_t sizeBytes, hipStream_t stream) {
	return ((__hipMemcpyDtoDAsync_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyDtoDAsync])(dst, src, sizeBytes, stream);
};

hipError_t hipTexObjectGetResourceViewDesc(HIP_RESOURCE_VIEW_DESC * pResViewDesc, hipTextureObject_t texObject) {
	return ((__hipTexObjectGetResourceViewDesc_t)hip_api_table.api_ptr[HIP_API_ID_hipTexObjectGetResourceViewDesc])(pResViewDesc, texObject);
};

hipError_t hipStreamAddCallback(hipStream_t stream, hipStreamCallback_t callback, void * userData, unsigned int flags) {
	return ((__hipStreamAddCallback_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamAddCallback])(stream, callback, userData, flags);
};

hipError_t hipTexRefSetFormat(textureReference* texRef, hipArray_Format fmt, int NumPackedComponents) {
	return ((__hipTexRefSetFormat_t)hip_api_table.api_ptr[HIP_API_ID_hipTexRefSetFormat])(texRef, fmt, NumPackedComponents);
};

hipError_t hipFuncGetAttributes(struct hipFuncAttributes * attr, const void * func) {
	return ((__hipFuncGetAttributes_t)hip_api_table.api_ptr[HIP_API_ID_hipFuncGetAttributes])(attr, func);
};

hipError_t hipStreamCreateWithPriority(hipStream_t * stream, unsigned int flags, int priority) {
	return ((__hipStreamCreateWithPriority_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamCreateWithPriority])(stream, flags, priority);
};

hipError_t hipGetTextureReference(const textureReference** texref, const void * symbol) {
	return ((__hipGetTextureReference_t)hip_api_table.api_ptr[HIP_API_ID_hipGetTextureReference])(texref, symbol);
};

hipError_t hipGraphAddKernelNode(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, const hipKernelNodeParams * pNodeParams) {
	return ((__hipGraphAddKernelNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddKernelNode])(pGraphNode, graph, pDependencies, numDependencies, pNodeParams);
};

hipError_t hipMemcpyToArray(hipArray_t dst, size_t wOffset, size_t hOffset, const void * src, size_t count, hipMemcpyKind kind) {
	return ((__hipMemcpyToArray_t)hip_api_table.api_ptr[HIP_API_ID_hipMemcpyToArray])(dst, wOffset, hOffset, src, count, kind);
};

hipError_t hipIpcCloseMemHandle(void * devPtr) {
	return ((__hipIpcCloseMemHandle_t)hip_api_table.api_ptr[HIP_API_ID_hipIpcCloseMemHandle])(devPtr);
};

hipError_t hipGraphDestroy(hipGraph_t graph) {
	return ((__hipGraphDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphDestroy])(graph);
};

hipError_t hipMemAdvise(const void * dev_ptr, size_t count, hipMemoryAdvise advice, int device) {
	return ((__hipMemAdvise_t)hip_api_table.api_ptr[HIP_API_ID_hipMemAdvise])(dev_ptr, count, advice, device);
};

hipError_t hipGraphDestroyNode(hipGraphNode_t node) {
	return ((__hipGraphDestroyNode_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphDestroyNode])(node);
};

hipError_t hipFuncGetAttribute(int * value, hipFunction_attribute attrib, hipFunction_t hfunc) {
	return ((__hipFuncGetAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipFuncGetAttribute])(value, attrib, hfunc);
};

hipError_t hipCtxEnablePeerAccess(hipCtx_t peerCtx, unsigned int flags) {
	return ((__hipCtxEnablePeerAccess_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxEnablePeerAccess])(peerCtx, flags);
};

hipError_t hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags(int * numBlocks, hipFunction_t f, int blockSize, size_t dynSharedMemPerBlk, unsigned int flags) {
	return ((__hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_t)hip_api_table.api_ptr[HIP_API_ID_hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags])(numBlocks, f, blockSize, dynSharedMemPerBlk, flags);
};

hipError_t hipCtxSynchronize() {
	return ((__hipCtxSynchronize_t)hip_api_table.api_ptr[HIP_API_ID_hipCtxSynchronize])();
};

hipError_t hipDestroyExternalMemory(hipExternalMemory_t extMem) {
	return ((__hipDestroyExternalMemory_t)hip_api_table.api_ptr[HIP_API_ID_hipDestroyExternalMemory])(extMem);
};

hipError_t hipStreamDestroy(hipStream_t stream) {
	return ((__hipStreamDestroy_t)hip_api_table.api_ptr[HIP_API_ID_hipStreamDestroy])(stream);
};

hipError_t hipGraphAddMemcpyNodeToSymbol(hipGraphNode_t * pGraphNode, hipGraph_t graph, const hipGraphNode_t * pDependencies, size_t numDependencies, const void * symbol, const void * src, size_t count, size_t offset, hipMemcpyKind kind) {
	return ((__hipGraphAddMemcpyNodeToSymbol_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphAddMemcpyNodeToSymbol])(pGraphNode, graph, pDependencies, numDependencies, symbol, src, count, offset, kind);
};

hipError_t hipGraphEventRecordNodeSetEvent(hipGraphNode_t node, hipEvent_t event) {
	return ((__hipGraphEventRecordNodeSetEvent_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphEventRecordNodeSetEvent])(node, event);
};

hipError_t hipDeviceGetP2PAttribute(int * value, hipDeviceP2PAttr attr, int srcDevice, int dstDevice) {
	return ((__hipDeviceGetP2PAttribute_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetP2PAttribute])(value, attr, srcDevice, dstDevice);
};

int hipGetStreamDeviceId(hipStream_t stream) {
	return ((__hipGetStreamDeviceId_t)hip_api_table.api_ptr[HIP_API_ID_hipGetStreamDeviceId])(stream);
};

hipError_t hipGraphNodeGetEnabled(hipGraphExec_t hGraphExec, hipGraphNode_t hNode, unsigned int * isEnabled) {
	return ((__hipGraphNodeGetEnabled_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphNodeGetEnabled])(hGraphExec, hNode, isEnabled);
};

hipError_t hipDeviceGetMemPool(hipMemPool_t * mem_pool, int device) {
	return ((__hipDeviceGetMemPool_t)hip_api_table.api_ptr[HIP_API_ID_hipDeviceGetMemPool])(mem_pool, device);
};

hipError_t hipMipmappedArrayGetLevel(hipArray_t * pLevelArray, hipMipmappedArray_t hMipMappedArray, unsigned int level) {
	return ((__hipMipmappedArrayGetLevel_t)hip_api_table.api_ptr[HIP_API_ID_hipMipmappedArrayGetLevel])(pLevelArray, hMipMappedArray, level);
};

hipError_t hipGraphExecMemcpyNodeSetParamsToSymbol(hipGraphExec_t hGraphExec, hipGraphNode_t node, const void * symbol, const void * src, size_t count, size_t offset, hipMemcpyKind kind) {
	return ((__hipGraphExecMemcpyNodeSetParamsToSymbol_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecMemcpyNodeSetParamsToSymbol])(hGraphExec, node, symbol, src, count, offset, kind);
};

hipError_t hipGraphExecMemsetNodeSetParams(hipGraphExec_t hGraphExec, hipGraphNode_t node, const hipMemsetParams * pNodeParams) {
	return ((__hipGraphExecMemsetNodeSetParams_t)hip_api_table.api_ptr[HIP_API_ID_hipGraphExecMemsetNodeSetParams])(hGraphExec, node, pNodeParams);
};

